### ISSUE TITLE
minify-type-constructors shouldn’t rewrite `String(symbol)`

### ISSUE THREAD

**Issue by mathiasbynens** [babel/babili#112]
## Input

``` js
var symbol = Symbol();
String(symbol);
// → 'Symbol()'
```
## Current output:

``` js
var symbol = Symbol();
symbol+"";
// → throws TypeError: Cannot convert a Symbol value to a string
```

**Comment by mathiasbynens** [comment]
Btw, `String(x)` and `x + ""` (or `"" + x`) are not equivalent in general. Here’s another snippet that doesn’t use symbols but still produces different output after minification:

```js
var obj = {
  valueOf: _ => { console.log('valueOf'); return {}; },
  toString: _ => { console.log('toString'); return {}; }
};

try { String(obj); } catch (exception) { console.log(exception); }
// 1. toString
// 2. valueOf
// 3. TypeError: Cannot convert object to primitive value

// After minification, this becomes something like:
try { obj+""; } catch (exception) { console.log(exception); }
// 1. valueOf
// 2. toString
// 3. TypeError: Cannot convert object to primitive value
```

**Comment by boopathi** [comment]
Thanks!

PR - #113 

Is it that this transformation shouldn't be applied to any pattern of `String(x)` ?

Since we don't know type `x` in `String(x)` during compile time, I guess we shouldn't transform this at all.

**Comment by mathiasbynens** [comment]
I just wanted to make sure these edge cases are considered.

They might be rare enough in practice that the Babel team may decide not to care about them. But in that case, a note/warning in the README would be nice.

**Comment by hzoo** [comment]
Yeah this is similar to template strings http://babeljs.io/docs/plugins/transform-es2015-template-literals/ although in this case users are intentionally using String.

**Comment by boopathi** [comment]
This is merged and now there is an option to disable only `String()` type constructors.
