### ISSUE TITLE
Minimum browser support is unclear

### ISSUE THREAD

**Issue by alanhussey** [babel/babili#114]
The README has an implicit requirement of only targeting new-enough browsers, but doesn't explicitly say what those browsers are (or what features are needed). 

> When it's possible to only target browsers that support newer ES features, code sizes can be smaller because you don't have to transpile and then minify.

I looked through some of the rules and only found a single mention of IE8 being unsupported.

**Comment by hzoo** [comment]
Sorry still working on the readme and all that so bear with us.

It targets the latest browsers but the point is that you can always use babel to transpile down first and then run babili. We will need to work on the integration and all that

**Comment by kangax** [comment]
Clarified in https://github.com/babel/babili/commit/2837057e21568acca32cc1ebf866b16c30793141
