### ISSUE TITLE
Compression breaks commonmark npm package

### ISSUE THREAD

**Issue by swernerx** [babel/babili#115]
I am using react-markdown which uses commonmark. When compiling the code with babili it breaks in some crazy way. It leads to an endless loop for both NodeJS and Chrome.

I am still investigating to narrow this down a little more.

Just wondering: Is there some special utf-8/unicode related functionality in babili?

**Comment by swernerx** [comment]
Excludes the dependencies of commonmark does not help. Possibily it is related to unicode sequences found in https://github.com/dougmoscrop/fold-case.

**Comment by mathiasbynens** [comment]
Honest question: why use fold-case instead of the original https://github.com/mathiasbynens/swapcase?

**Comment by swernerx** [comment]
I actually don't know. It seems to be inlined in the commonmark implementation. I am not the author ;)

**Comment by boopathi** [comment]
Seems like some bug with `simplify`. Disabling simplify from the preset got it working.

**Comment by boopathi** [comment]
Some issue with simplify. Was able to boil down the issue ... I think it breaks this function - https://github.com/jgm/commonmark.js/blob/7b27c58733b7a9f640d91bcec6923458d6b796b9/lib/inlines.js#L829
