### ISSUE TITLE
Using babili then babel then minify again?

### ISSUE THREAD

**Issue by eloytoro** [babel/babili#117]
As the title says, is it worth it? Could my app become smaller if I minify twice?

**Comment by timdorr** [comment]
> "I remixed a remix, it was back to normal." - Mitch Hedberg

No, you cannot continually minify to obtain smaller and smaller files. After the first pass, it will already be at optimal compression. If it's not compressed to its smallest form, then that's a bug! :smile:

**Comment by kangax** [comment]
We talked about the issue of multiple passes and how it's possible to get smaller size that way. This is something we're planning to revisit in https://github.com/babel/babili/issues/61

**Comment by eloytoro** [comment]
@kangax so is this an actual issue? Because by the looks of it uglify by minimizing transpiled code isn't considering some enhancements made possible by this proyect, maybe if minimized by babili first the overall output could be smaller.
I would test it out but only if I get the green light from the maintainers

**Comment by timdorr** [comment]
@eloytoro To clarify my statements, multiple passes is something internal to babili that you, as a user, shouldn't have to worry about. It should have some of heuristic for determining how many passes should be run (probably with some configuration for you to trade off speed with compression). But you shouldn't have to run the tool twice to achieve that compression.

Also, babili -> Uglify (or vice versa) should be unnecessary as this project matures. The goal is obviously to exceed the file size reduction of other tools, so running two tools would have minimal gains (or even some losses!)

**Comment by eloytoro** [comment]
@timdorr but babili outputs ES2015+ code, which is usually not the final output for most front-end apps

**Comment by eloytoro** [comment]
In the README you have this
ES2015+ code -> Babel -> Uglify -> Minified ES5 Code
versus this
ES2015+ code -> Babili -> Minified ES2015+ Code

It's clear that the final output is not the same, i would still have to pass it to ES5 as a final step
ES2015+ code -> Babili -> Minified ES2015+ Code -> Babel -> Uglify -> Minified ES5 Code

**Comment by kangax** [comment]
What we do at Facebook is ES2015+ code -> Babel transforms (ES2015+ & custom) -> AST -> Babili -> minified ES5 code.

**Comment by hzoo** [comment]
@eloytoro Ok it sounds like what I wrote didn't make it any clearer in the readme 😛.

If you need to minify to es2015, you would just run Babel and then Babili.

It's potentially a switch for uglify
// current
ES2015+ code -> Babel ->  Uglify -> Minified ES5 Code
// with babili
ES2015+ code -> Babel ->  Babili -> Minified ES5 Code

If you happen to target es2015 then
ES2015+ code -> Babili -> Minified ES2015+ Code

**Comment by Hypnosphi** [comment]
>If you need to minify to es2015, you would just run Babel and then Babili

Unfortunaltely, in that case Babili can't drop unused classes: https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=true&presets=es2015&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=true&spec=true&code_lz=GYVwdgxgLglg9mABMAFASkQbwFCMRAGwEMBnExAQSwF9dEAnAUyhHqQCZtbsg

**Comment by timdorr** [comment]
@Hypnosphi Not sure what you mean. This is the output, ignoring the helper function:
```js
// input.js
function f() {
  class A {}
  return 2
}

// output.js
function f(){return 2}
```

**Comment by Hypnosphi** [comment]
Ok, here's a more verbose example: https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=true&presets=es2015%2Creact&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=true&spec=true&code_lz=JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYChRJZdniATJFCq16TFjAC0fQgwDcbNmgA2KAM6q4AMQgQ4SAB4wyfDQSKlyuNnDi8BUABQBKKzZvMYAVyjE4AHj5gADcAPhgAC2ANNAgBOCi4T2JmdHCUACMlJD8AekDQ-RsKNmLFFXU4ACEUKD1DY1NCSAt4HGtbY0FnVzcPb18A4JyQ9uLSuy6_aqhh7Gk0TxAyGAA6AHMkGABRLKXyBwYAYhQwMAYnJzYgA

**Comment by timdorr** [comment]
The class exists at the top level. Babili won't remove it because it doesn't know if it's used in some other script file/tag. It's the same reason the f() function remains in the previous example, even though it's never called.

**Comment by Hypnosphi** [comment]
Well, why it's removed here then? https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=true&presets=react&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=true&spec=true&code_lz=JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYChRJZdniATJFCq16TFjAC0fQgwDcbNmgA2KAM6q4AMQgQ4SAB4wyfDQSKlyuNnDi8BUABQBKKzZvMYAVyjE4AHj5gADcAPhgAC2ANNAgBOCi4T2JmdHCUACMlJD8AekDQ-RsKNmLFFXU4ACEUKD1DY1NCSAt4HGtbY0FnVzcPb18A4JyQ9uLSuy6_aqhh7Gk0TxAyGAA6AHMkGABRLKXyBwYAYhQwMAYnJzYgA

**Comment by Hypnosphi** [comment]
And here it's not top level (notice how var foo gets successfully removed)
https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=true&presets=es2015%2Creact&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=true&spec=true&code_lz=JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYChRJZdniATJFCq16TFjAC0fQgwDcbNgApqAV2IZgJOIoCUuNnDgA3FFBoQIcALyM1zdAAsUAIwA2SYylcqkcg3H80VxQAZxC4ADELOCQADxgyPnCCIlJyfUNDXgEoXQzM_0y4ZhgVKGI4AB4-YCMAPhgHYHC0CAE4Zrg7Fic3JEqAehr6-SKKf3GKHV15NiDQ8IAhUxj4xOTCSDT4HH9swTzdopKyiuragbqJtnG2fdzK5ahL7Gk0FRAyGAA6AHMkGAAUXcn3IigYAGIUGAwAwdDo2EA
