### ISSUE TITLE
Bad arrow function transform inside another function

### ISSUE THREAD

**Issue by jfsiii** [babel/babili#130]
As you can [see in the REPL](http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=false&loose=false&spec=false&code=function%20outer()%20%7B%0A%20%20const%20inner%20%3D%20(d)%20%3D%3E%20d.x%3B%0A%20%20return%20inner%3B%0A%7D%0A&playground=false), running babili on

```js
function outer() {
  const inner = (d) => d.x;
  return inner;
}
```
produces
```js
"use strict";function outer(){return function(a)a.x}
```

Which causes an `Unexpected identifier` error because of `function(a)a.x`.

```
const outer = () => {
  const inner = (d) => d.x;
  return inner;
}
```
also [fails in the same way](http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=false&loose=false&spec=false&code=const%20outer%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20inner%20%3D%20(d)%20%3D%3E%20d.x%3B%0A%20%20return%20inner%3B%0A%7D%0A&playground=false)

**Comment by hzoo** [comment]
For minimal repro, we don't need any other presets: `function outer(){return function(a)a.x}`
