### ISSUE TITLE
Simplified JavaScript API

### ISSUE THREAD

**Issue by matthewp** [babel/babili#137]
Would you be open to a JavaScript API that wraps the babel API similar to how the CLI tool wraps babel-cli? For non Babel users trying to use babili programmatically is a little more complicated than it could be, because you have to first learn a different tool that's used in a different way.

**Comment by boopathi** [comment]
I like the idea. But just thinking how the API could look like - 

`babili(code, babiliOpts, babelOpts)` - and then users have to refer babel API docs again for babelOpts - sourceMaps, and lots of other [options](http://babeljs.io/docs/usage/options/) which wouldn't IMO make sense to duplicate for babili (to provide under babiliOpts).

This API will just be - 

```js
const {transform} = require("babel-core");
const preset = require("babel-preset-babili");
module.exports = function Babili(code, babiliOpts = {}, babelOpts = {}) {
  if (babelOpts.presets) {
    babelOpts.presets.push([preset, babiliOpts]);
  } else {
    babelOpts.presets = [[preset, babiliOpts]];
  }
  return transform(code, babelOpts);
};
```

IMO, babiliOpts (preset options) and babelOpts should not be merged to one object as one might expect to pass in same options to preset and NodeAPI.

**Comment by hzoo** [comment]
What about just using babel-core then?

**Comment by johanssj** [comment]
I'm hardly an expert (on Babili) but things that you can run in a terminal/shell are convenient so this sounds like a very good idea

**Comment by matthewp** [comment]
I would think you would only have babili's options in this API. The intent is not to do everything babel can do; use babel if you need that flexibility. It could be as simple as:

```js
let babili = require('babili');

let { code, map } = babili("class Foo {} ...", {});
```

**Comment by Daniel15** [comment]
For what it's worth, I did something like this for the babel-standalone build of Babili: https://github.com/Daniel15/babel-standalone/blob/master/src/babili.js#L31-L39

**Comment by jonathanong** [comment]
one thing that might happen in the future is options per transform. for example, uglify has an option to mangle top-level variables. we will need this in the future to support transforming both modules and top-level code. a simplified API would be nice under this circumstance, though it's just selecting plugins under the hood

**Comment by nitin42** [comment]
How about this ?

```javascript
var babili = require('babili');

var result = babili.minify(code, {options});
console.log(result.code); // Outputs the result

var map = babili.minify(code, { outSrcMap: /** path to the output file */ });
console.log(result.map);

```

Other options may include mangling or some other minifying options.
