### ISSUE TITLE
minify-dead-code-elimination breaks code

### ISSUE THREAD

**Issue by f0rr0** [babel/babili#145]
I have a repo where I am testing babili. 
https://github.com/sidjain26/koa-jsonwebtoken/tree/babili

Everything works as expected without babili but using it causes unexpected outputs. Clone the repo and run:

```
npm i
npm run build
npm run test
```

Run the third curl command, you will see 
```
protected
```

Then in `webpack.config.js`, add the commented out plugins section. Repeat the steps above.

**Comment by sidjain26** [comment]
Tried debugging this a bit. This part of my code is missing from the final build. Can't fathom why.

https://github.com/sidjain26/koa-jsonwebtoken/blob/f32b238b586dba346145899c960d5522c50bcac9/main.js#L25-L30

```
  const {
    secret,
    extractToken,
    key = "user",
    checkRevoked = false
  } = opts;
```

**Comment by sidjain26** [comment]
uglifyjs2 harmony branch handles this correctly.

**Comment by boopathi** [comment]
I think this is the same issue as #151 and it's fixed in master now.
