### ISSUE TITLE
Class tokens are weirdly assigned

### ISSUE THREAD

**Issue by Feenposhleen** [babel/babili#147]
Hey all, sorry if this has already been reported. Couldn't find it if so.

    class A {}
    class B {}

    const a = new A();
    const b = new B();

becomes

`class c{}class c{}const a=new c,b=new c;`

This of course breaks stuff, as the same token is declared twice. I thought at first that this could be caused by some attempt to dedupe classes, but even if you flesh them out to be unique, the problem persists.

**Comment by hzoo** [comment]
Wow definetely a bug (assuming in the name mangler/scoping).

**Comment by goto-bus-stop** [comment]
Fixed by d8c7ebe6e27f768e9f459e574e08ba74de0cd686, looks like?

**Comment by boopathi** [comment]
Yes!.
