### ISSUE TITLE
Improper let scoping

### ISSUE THREAD

**Issue by ShimShamSam** [babel/babili#153]
```JavaScript
let x = 0;

for(let i = 0; i < 10; ++i) {
	x++;
}

console.log(x);
```
is converted to:
```JavaScript
for(let x=0,a=0;10>a;++a)x++;console.log(x);
```

**x** is being moved into the first part of the **for** loop which causes it to be scoped only to the **for block**. The call to **console.log(x)** is outside of the block and thus throws a **ReferrenceError**.

**Comment by hzoo** [comment]
Sounds like we don't want to combine variable declarations in the loop if the outer declaration is also a let/const and only if it's a var - or maybe only do it if not referenced outside?

**Comment by ShimShamSam** [comment]
> maybe only do it if not referenced outside
That would work nicely

**Comment by loganfsmyth** [comment]
Note that there is a slight difference in those two if the loop body had an async callback in it since mutating x from inside the callback would not work the same way as when it is declared outside the loop.

**Comment by ShimShamSam** [comment]
Good point. I guess it's safer to not do that kind of transformation.
