### ISSUE TITLE
// Comments not stripped

### ISSUE THREAD

**Issue by ShimShamSam** [babel/babili#154]
```JavaScript
var foo = 1; // Test 1
++foo;

var bar = 1;
// Test 2
++bar;
```
Becomes:
```JavaScript
var foo=1;// Test 1
++foo;var bar=1;// Test 2
++bar;
```

I expect the comments to be stripped out. Is there a setting I'm missing?

**Comment by hzoo** [comment]
There's a `--no-comments` option, and seems like comments: false isn't working in babelrc https://github.com/babel/babili/issues/67
