### ISSUE TITLE
JSX in function results in Unexpected JSXIdentifier

### ISSUE THREAD

**Issue by radekmie** [babel/babili#158]
This code:

```js
const X = x();
<X />
```

Is correctly minified to:

```js
"use strict";var X=x();React.createElement(X,null);
```

This code:

```js
const render = () => {
    const X = x();

    return (
        <X />
    );
}
```

Results with:

> Unexpected JSXIdentifier. Expected an Identifier

This occurs in Babel REPL - when I used CLI, I've received minified version of something like this:

```js
const a = () => {  // minified name - OK
    const b = x(); // minified name - OK

    return (
        <X /> // oops!
    );
}
```

**Comment by boopathi** [comment]
The first one works because it is in the global scope and is not mangled. 

I'm not sure why that errors in REPL.

For the last case, consider this workaround for now - use `passPerPreset` option when using with react preset. Have to debug why mangler skips that path after transforming to React.createElement.

**Comment by radekmie** [comment]
> The first one works because it is in the global scope and is not mangled.

Good to know.

> For the last case, consider this workaround for now - use passPerPreset=true option when using with react preset. Have to debug why mangler skips that path after transforming to React.createElement.

I'm using `babel-preset-babili` (`"presets": ["babili", ...]`) - how can I pass this option?

**Comment by boopathi** [comment]
```js
console.log(require('babel-core').transform(`
const render = () => {
  const Foo = x();
  return <Foo/>;
}`, {
  presets: ['react', 'babili'],
  passPerPreset: true
}).code);
```

And I get the output

```js
const render = () => {
    const a = x();
    return React.createElement(a, null);
};
```

**Comment by radekmie** [comment]
OK, maybe I mistyped `passPerPreset` or something.
