### ISSUE TITLE
optimize (as well as minify) JS?

### ISSUE THREAD

**Issue by jonathanong** [babel/babili#164]
https://github.com/nolanlawson/optimize-js

would be cool to see options like this as long as they are relevant, but this expands the scope of this module to an optimizer as well

**Comment by bardiharborow** [comment]
It seems like this is an example of trying to be too clever by half. I'm more inclined to write logical code and let people like the V8 team handle optimisation on their end.

**Comment by boopathi** [comment]
https://github.com/babel/babel/issues/4615

**Comment by vigneshshanmugam** [comment]
check https://github.com/babel/babel/issues/4615#issuecomment-273278103 and https://github.com/webpack/webpack/issues/2873#issuecomment-303185677
