### ISSUE TITLE
minify-simplify + minify-guarded-expressions incorrectly transform a switch statement

### ISSUE THREAD

**Issue by asapach** [babel/babili#171]
I've distilled my repro case to this:
```js
function foo(bar) {
	bar = bar || 'baz';

	switch (bar) {
		case 'spam':
			return true;
		case 'ham':
		case 'eggs':
			return false;
	}
	return false;
}
```
Notice that the function only returns `true` if `bar == 'spam'`.

When I run it through `minify-simplify` plugin (`babel --plugins=minify-simplify`) it produces a correct result:
```js
function foo(bar) {
	return bar = bar || 'baz', bar === 'spam' || (bar === 'ham' || bar === 'eggs') && false;
}
```

When I run the source through `minify-guarded-expressions` separately (`babel --plugins=minify-guarded-expressions`) it has no effect.

However when I run `minify-simplify` and `minify-guarded-expressions` at the same time (`babel --plugins=minify-guarded-expressions,minify-simplify`) I get this:
```js
function foo(bar) {
	return bar = bar || 'baz', bar === 'spam' || bar === 'ham' || bar === 'eggs';
}
```
Notice that the function now returns `true` for all the cases, not just `'spam'`.

Here's a [REPL](http://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=true&presets=es2015&code=function%20foo(bar)%20%7B%0A%20%20bar%20%3D%20bar%20%7C%7C%20%27baz%27%3B%0A%0A%20%20switch%20(bar)%20%7B%0A%20%20%20%20case%20%27spam%27%3A%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20case%20%27ham%27%3A%0A%20%20%20%20case%20%27eggs%27%3A%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20return%20false%3B%0A%7D)

**Comment by asapach** [comment]
I guess this can be further simplified to:
```js
foo === 'bar' || foo === 'baz' && false
```
Running `babel --plugins=minify-guarded-expressions` produces:
```js
foo === 'bar' || foo === 'baz';
```
Which is clearly incorrect, since the right branch is effectively dead code. Here's a [REPL](http://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=true&presets=es2015&code=foo%20%3D%3D%3D%20%27bar%27%20%7C%7C%20foo%20%3D%3D%3D%20%27baz%27%20%26%26%20false)

**Comment by kangax** [comment]
Yeah, we should be smarter here. If the value is utilized (passed to function, assigned, returned, etc.) probably need to ignore this optimization entirely.
