### ISSUE TITLE
not enough optimization

### ISSUE THREAD

**Issue by jt3k** [babel/babili#173]
![](https://i.imgur.com/ivwoFAu.png)

**Comment by boopathi** [comment]
This should not be optimized because if the property has a setter else where which creates side-effects, then the output would be very wrong.

```js
Object.defineProperty(susk.prototype, 'fusk', {
  set(val) {
    // side-effecty setter
    console.log(val);
  }
})
```

And we are looking towards adding more optimizations in future.

**Comment by kangax** [comment]
I think this should be part of DCE and one of unsafe transformations (just like `Array(...)` → `[...]`)

**Comment by boopathi** [comment]
Makes sense. But how often do you find two of the same assignment expressions right next to each other?
(re-open if required)

**Comment by kangax** [comment]
Could be a copy-paste or a typo or part of automated codemod
