### ISSUE TITLE
minify-guarded-expressions is too agressive

### ISSUE THREAD

**Issue by asapach** [babel/babili#174]
Input:
```js
foo = (bar.baz || '').length;
```
Output with `minify-guarded-expressions` enabled:
```js
foo = bar.baz.length;
```
The problem is that `bar.baz` can be undefined, so `bar.baz.length` will throw an error.

For some reason I can't reproduce it on the [REPL page](http://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=true&presets=latest&code=foo%20%3D%20(bar.baz%20%7C%7C%20%27%27).length%3B), but it is reproducible via CLI: `babel --plugins=minify-guarded-expressions`

**Comment by boopathi** [comment]
Related: #171
