### ISSUE TITLE
babili overminifies statements with || ''

### ISSUE THREAD

**Issue by muntact** [babel/babili#176]
With version 0.0.4 of babel-preset-babili, Safe setting a variable to a null string is removed by the minification process. 

The following code:

```
this.value = a || '';
```

is minified to:

```
this.value = a;
```

**Comment by loganfsmyth** [comment]
Looks like a dup of https://github.com/babel/babili/issues/174 ?

**Comment by boopathi** [comment]
Yes. let's track it in #174
