### ISSUE TITLE
Handling special characters, UTF-8?

### ISSUE THREAD

**Issue by dmackerman** [babel/babili#187]
I'm running into an issue which (I think) has to do with babili not handling character encoding properly. When I run my build through Webpack, and load the files in the browser, I'm getting `d3.js:4408 Uncaught SyntaxError: Unexpected string` (from source maps). 

The code in question:

``` js
  function d3_geo_forwardRotationλ(δλ) {
    return function(λ, φ) {
      return λ += δλ, [ λ > π ? λ - τ : λ < -π ? λ + τ : λ, φ ];
    };
  }
```

I've tried the `EncodingPlugin` but that doesn't seem to do it. I've been digging and found out that `Uglify` has an `ascii_only` option - is this something babili needs? I've tried setting the `<meta charset="utf-8">` and even `charset="utf-8"` on the `<script>` tags, but no luck.

**Comment by kangax** [comment]
If you're on the latest Babel, it should be escaping these characters properly.

https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=%20%20function%20d3_geo_forwardRotation%CE%BB(%CE%B4%CE%BB)%20%7B%0A%20%20%20%20return%20function(%CE%BB%2C%20%CF%86)%20%7B%0A%20%20%20%20%20%20return%20%CE%BB%20%2B%3D%20%CE%B4%CE%BB%2C%20%5B%20%CE%BB%20%3E%20%CF%80%20%3F%20%CE%BB%20-%20%CF%84%20%3A%20%CE%BB%20%3C%20-%CF%80%20%3F%20%CE%BB%20%2B%20%CF%84%20%3A%20%CE%BB%2C%20%CF%86%20%5D%3B%0A%20%20%20%20%7D%3B%0A%20%20%7D
