### ISSUE TITLE
Incorrect inlining of unreachable statement

### ISSUE THREAD

**Issue by kangax** [babel/babili#192]
``` js
var x = 0;
function f1(){
  function f2(){
    return x;
  };
  return f2();
  var x = 1;
}
```

minifies to:

``` js
var x=0;function f1(){;return function(){return 1}()}
```

Notice inlined `x=1` which shouldn't be the case since the assignment is after return statement and so it's never executed. However `var x` still declares variable so the inlined value should be `undefined` or nothing at all. 

Ideally, the entire f1 body should be eliminated via DCE.

**Comment by boopathi** [comment]
Related - https://github.com/babel/babel/issues/4420

**Comment by boopathi** [comment]
https://github.com/babel/babel/pull/4875

**Comment by boopathi** [comment]
Interesting!. Even after that fix with path.evaluate in babel, it still has the same bug.

**Comment by kangax** [comment]
Here's an even better (more minimal) example:

```
(function() {
  return x;
  var x = 1;
})()
```

We basically seem to disregard hoisting when DCE-ing stuff. I'm looking into it.

**Comment by boopathi** [comment]
So, this is not because of path.evaluate in babel. This is because of something in dce only. I'm guessing the one time used constant is just replaced without checking if it occurs before or after.
