### ISSUE TITLE
Doesn't mung some vars.

### ISSUE THREAD

**Issue by jdalton** [babel/babili#204]
You can see [here](https://lodash.com/sw.js) that the `BUILD_REV` var stays unminified.

**Comment by boopathi** [comment]
Top-level vars are not mangled (yet).

**Comment by kangax** [comment]
@boopathi should be an easy change as long as we figure out how to call this optional flag

**Comment by boopathi** [comment]
yes. `topLevel` ?

**Comment by kangax** [comment]
I guess that would do.
