### ISSUE TITLE
`provided an invalid property of "name"` when using via babel.transform()

### ISSUE THREAD

**Issue by hatched** [babel/babili#205]
When using the babili preset via the CLI with it defined in the `.babelrc` everything works as it should. However when run via the `transform()` command it throws the following error:

```
~/node_modules/babel-core/lib/transformation/plugin.js:138
      throw new Error(messages.get("pluginInvalidProperty", loc, i, key));

Error: Plugin 0 specified in "~/node_modules/babel-preset-babili/lib/index.js" provided an invalid property of "name"
```

```JavaScript
const babel = require('babel-core');
const plugins = [
  'transform-react-jsx'
];
...
babel.transform(data, {
      presets: ['babel-preset-babili'],
      plugins,
      compact: true,
      comments: false
    });
```

```
node v6.2.0
npm 3.8.9
"babel-cli": "^6.16.0",
"babel-plugin-transform-react-jsx": "^6.8.0",
"babel-preset-babili": "0.0.5",
```

**Comment by boopathi** [comment]
Though your dependencies say babel-cli 6.16.0, can you check the babel-core version. This error happens only for babel-core version < 6.14.0.

I remember @kangax mentioning on slack that he got this error once with babel-core 6.14.0.

**Comment by hatched** [comment]
Thanks @boopathi!

I had checked `babel-core` and it was registering as `6.17.0`, HOWEVER it appears that the` babel-core` installed with `karma-babel-preprocessor` is `6.11.4` and it is the one npm treats as the 'top level' one. Manually loading the proper babel-cli appears to have resolved the issue.

```JavaScript
const babel = require('babel-cli/node_modules/babel-core');
```

This is of course until something changes and this version is flattened out instead of the one in the karma package :)

**Comment by AndrewEastwood** [comment]
@hatched is your karma-babel-preprocessor module from future? I cannot find that version at all. Current version is 6.0.1 and there is nothing about higher versions.

**Comment by hatched** [comment]
@AndrewEastwood This was from some time ago and it doesn't appear to be an issue any longer. You'll note that I didn't state the karma-babel-preprosessor version, those are for babel-core :)
