### ISSUE TITLE
var declaration inlined incorrectly in conditional

### ISSUE THREAD

**Issue by kangax** [babel/babili#213]
```js
if (x) {
  y;
} 
else {
  const z = foo(function() { z });
}
```

incorrectly minifies to:

```js
if(x)y;else const a=foo(function(){});
```

`else const ...`  is a SyntaxError

**Comment by boopathi** [comment]
I'd say if it's 

```js
else {
  const a = foo();
}
```

can be reduced to

```js
else foo();
```

**Comment by loganfsmyth** [comment]
@boopathi There's an edge case here that I wanted to mention, those two aren't equivalent because one results in a value and one does not.

```
eval(`
  var fn = function(){ return 4; };
  if (false){}
  else {const foo = fn();}
`) === undefined;
```

```
eval(`
  var fn = function(){ return 4; };
  if (false){}
  else fn();
`) === 4;
```

This matters in the case of `eval` and in the proposed `do` expression syntax.

**Comment by kangax** [comment]
I don't think we account for "top-level" evaluation result. Just like we'll remove unreferenced var at the end of all statements changing value or hoisting vars. We only account for values when they're assigned, returned, or passed as an argument.

**Comment by kangax** [comment]
What I'm saying — if we were to account for it in this case then we'll probably need to make it consistent in other cases too.
