### ISSUE TITLE
Removing Comments

### ISSUE THREAD

**Issue by gauntface** [babel/babili#217]
Hi,

I'm probably missing something simple here but after getting babili working with my gulp build step the final output is still including comments, is there a particular option I should be setting or is there an expectation to use something else to strip comments?

    gulp.src([
      path.join(__dirname, 'src', '**', '*.js'),
      path.join(__dirname, '..', '..', 'lib', '**', '*.js')
    ])
    .pipe(sourcemaps.init())
    .pipe(rollup({
      entry: path.join(__dirname, 'src', 'index.js')
    }))
    .pipe(babel({
      presets: ['babili']
    }))
    .pipe(sourcemaps.write())
    .pipe(rename(pkg.main))
    .pipe(gulp.dest(destPath))

Cheers,
Matt

**Comment by kangax** [comment]
Just put `comments: false` after `presets: ['babili']`

**Comment by cuixiping** [comment]
how to use `comments:false` in babel-cli mode?

**Comment by mathiasbynens** [comment]
@cuixiping Passing `--no-comments` seems to work. Strange that `comments: false` in `.babelrc` seems to be ignored by the CLI.

**Comment by siddharthkp** [comment]
Getting an error 

```
Error: Options {"comments":false} passed to .../node_modules/babel-preset-babili/lib/index.js which does not accept options. (While processing preset: ".../node_modules/babel-preset-babili/lib/index.js")
```

This is what I have in my `package.json`

```json
"babel": {
    "presets": [
      "es2015",
      ["babili", {"comments": false}]
    ]
}
```

**Comment by activedecay** [comment]
what docs?

**Comment by Firanolfind** [comment]
It does not work. Why cant we configure it in Babili options?
Like 
```
.pipe(Babili({
	mangle: { 
		topLevel: true,
		except : [],
		eval : false,
		sort : true,
		toplevel : false,
		screw_ie8 : false,
		keep_fnames : false
	},
	//somewhere here?
	deadcode: true,
	removeConsole: false,
}))`

**Comment by trusktr** [comment]
@kangax Please reopen, not everyone uses Babili with Babel.

Some people may want to use Babili on it's own, and adding something like Babel just for the purpose of removing comments is completely impractical.

**Comment by boopathi** [comment]
@trusktr answered in #644

**Comment by nmonti** [comment]
Updated solution since the renaming:

```json
// .babelrc
{
  "presets": ["env", "minify"],
  "comments": false
}
```
