### ISSUE TITLE
Use case/function

### ISSUE THREAD

**Issue by donnieflorence** [babel/babili#223]
Hello,

I'm curious and really happy/interested about babili, so I have one question.

Does babili minify and uglify code? Because when running babili with my build step I don't seem to be saving as much as when using UglifyJSPlugin. Which is why I'm wondering if it also uglifies the code removing space, etc to save bytes. If not what is the encouraged/best way to go about uglyfying the code to once babili minifies it?

Also are there any tips for making sure that babili always outputs as small files as possible?

**Comment by boopathi** [comment]
You can pass in some babel opts - http://babeljs.io/docs/usage/options/

```js
minified: true,
compact: true,
comments: false, 
// or
shouldPrintComment() { return false; }


```

**Comment by donnieflorence** [comment]
@boopathi what would that look like in .babelrc? is it like in an options: {..}?

**Comment by boopathi** [comment]
If you're using `babili` as CLI, [babelrc wouldn't work](https://github.com/babel/babili#usage). You have to pass `--no-comments` from CLI.

If you're using `babel-preset-babili`, you can add the above options [in babelrc](https://github.com/babel/babili#usage-1) and pass in other options alongside presets. 

```json
{
  "presets": ["es2015"],
  "env": {
    "production": {
      "presets": ["babili"],
      "comments": false
    }
  }
}
```
