### ISSUE TITLE
Publish 0.0.7?

### ISSUE THREAD

**Issue by julien-f** [babel/babili#228]
It appears that the latest published version is 0.0.5, is there a reason for that?

**Comment by hzoo** [comment]
Which package? It's https://www.npmjs.com/package/babili 0.0.7? https://unpkg.com/babili@0.0.7/

**Comment by julien-f** [comment]
My bad, I meant `babel-preset-babili` :blush:

**Comment by hzoo** [comment]
The packages are independently versioned unlike babel itself so it's correct https://github.com/babel/babili/commit/4234a5f13a3bb05a6df976ae462b25da6fa8b561

**Comment by julien-f** [comment]
I see :)

Don't you think it would make sense for the preset to have the same version?
I thought that most of the logic were in it…

**Comment by hzoo** [comment]
I mean we can try but it's possible to change the preset version/cli without changing the other? Everything will change while it's 0.x though

**Comment by julien-f** [comment]
It was just a suggestion, I don't want to complicate your work.

Thank you for your time. :)

**Comment by hzoo** [comment]
@julien-f In the next release we can align the preset/cli to be the same version - if it makes it less confusing then we should but no guarantees it will stay that way after 1.x!

**Comment by julien-f** [comment]
Don't bother, I should have read the changelog more carefully :wink:

**Comment by hzoo** [comment]
@julien-f Ok made the preset/cli the same version (0.0.8) https://github.com/babel/babili/releases/tag/babili%400.0.8

**Comment by julien-f** [comment]
I've noticed :)

Thank you!
