### ISSUE TITLE
Invalid scoping caused by minify-simplify + transform-merge-sibling-variables

### ISSUE THREAD

**Issue by smrq** [babel/babili#231]
Babel options:
```json
{
	"plugins": [
		"babel-plugin-minify-simplify",
		"babel-plugin-transform-merge-sibling-variables"
	]
}
```

Input:

```js
function foo() {
	let x = 3;
	let arr = [1,2,3];
	while (arr.length)
		x += arr.pop();
	return x;
}
```

Output:

```js
function foo() {
	for (let x = 3, arr = [1, 2, 3]; arr.length;) x += arr.pop();

	return x;
}
```

The declaration of `x` is being pulled into the scope of the generated `for` loop, which causes it to leave scope before the `return` statement.

Repro on REPL: http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=&code=function%20foo()%20%7B%0A%20%20let%20x%20%3D%203%3B%0A%20%20let%20arr%20%3D%20%5B1%2C2%2C3%5D%3B%0A%20%20while%20(arr.length)%0A%20%20%20%20x%20%2B%3D%20arr.pop()%3B%0A%20%20return%20x%3B%0A%7D%0Aconsole.log(foo())%3B%0A&experimental=true&loose=false&spec=false&playground=false

**Comment by boopathi** [comment]
Fixed by #202
