### ISSUE TITLE
Destructuring assignment bug

### ISSUE THREAD

**Issue by FGRibreau** [babel/babili#232]
```js
const a = {
  lol: (input) => {
      const [hello, world] = input.split('|');
      if (hello === 't' || hello === 'top') {
        return 'top';
      }
      return 'bottom';
    }
}
```

Becomes (see [babel repl](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Clatest&experimental=true&loose=false&spec=false&code=%0Aconst%20a%20%3D%20%7B%0A%20%20lol%3A%20(input)%20%3D%3E%20%7B%0A%20%20%20%20%20%20const%20%5Bhello%2C%20world%5D%20%3D%20input.split('%7C')%3B%0A%20%20%20%20%20%20if%20(hello%20%3D%3D%3D%20't'%20%7C%7C%20hello%20%3D%3D%3D%20'top')%20%7B%0A%20%20%20%20%20%20%20%20return%20'top'%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20return%20'bottom'%3B%0A%20%20%20%20%7D%0A%7D)):

```js
'use strict';var a={lol:function lol(b){return b.split('|'),'t'===c||'top'===c?'top':'bottom'}};
```

**Bug**: `c` is never declared

**Note**: babel output is correct, the issue came only when babili was activated

**Comment by boopathi** [comment]
I fixed this in #155 ... Looks like I missed a spot.
