### ISSUE TITLE
babel-plugin-minify-constant-folding throws

### ISSUE THREAD

**Issue by kangax** [babel/babili#245]
```
try {
  x({ 'toString': 0 } + '');
} 
catch(e) { }
```

Looks like we throw on `path.evaluate()` when trying to fold the constants. Should we just try-catch it?

/cc @boopathi

**Comment by boopathi** [comment]
Looks like we just have to fix `path.evaluate` then ... http://astexplorer.net/#/ZnK9C0caaf ... try catch around path.evaluate looks like a hectic workaround ... path.evaluate is used in every plugin of babili ...

**Comment by kangax** [comment]
What would it return then? How do we differentiate between return value and something throwing?
