### ISSUE TITLE
Production setting for babili not working

### ISSUE THREAD

**Issue by donnieflorence** [babel/babili#249]
Hey, I'm having trouble making babili work on different environment settings:
I'm not sure if babili is working
  - Reason why I say this is because I check lib.js and lib.min.js they are the same size and when I open them in the editor their contents are the same. Both seem to preserve white space and variables, etc.
- I know both babel and rollup pick up the environment variables because in production babel is stripping the comments out, but in development it keeps it.

my babelrc is : 
```js
{
  "presets": [ "es2015-rollup"],
  "env": {
    "production": {
      "presets":["babili"],
      "comments": false,
      "minified": true,
      "compact": true
    }
  }
}

```
I want to note that both the lib.js(process.env.NODE_ENV is not production) and lib.min.js(process.env.NODE_ENV is set to production) are both **identical** line for line.

Also are there any other babili settings to compress an minimize size?

**Comment by donnieflorence** [comment]
babili doesn't seem to be changing the code at all

**Comment by boopathi** [comment]
Can you give some more details how you're using this babelrc file ? with babel-cli ? or create a repo which has this bug ?
