### ISSUE TITLE
Incorrectly reported duplicate declaration (when NOT using es2015)

### ISSUE THREAD

**Issue by kangax** [babel/babili#255]
This makes Babili throw:

```js
let x;
{
  for (x in y) {
    foo(x);
  }
}
```

**Comment by vigneshshanmugam** [comment]
@kangax I am not seeing any error with this.
```js
OUTPUT
for (var x in y) foo(x);
```

**Comment by boopathi** [comment]
I'm sure this threw an error from Simplify. Not sure what fixed it though. I'm not able to reproduce it in master.

**Comment by kangax** [comment]
This still throws for me on master:

```js
const babel = require('babel-core');

const input = `
let x;
{
  for (x in y) {
    foo(x);
  }
}
`;

const { code } = babel.transform(input, {
  presets: ['babili']
});

console.log(code);
```

**Comment by boopathi** [comment]
On master this doesn't appear for me... On 0.0.8 and 0.0.9 it throws. 

<img width="853" alt="screenshot 2016-11-30 14 04 00" src="https://cloud.githubusercontent.com/assets/294474/20753273/dea01f08-b705-11e6-9b85-92603b97c4ee.png">

- The `[1]` at the beginning of the line is the exit code of the previous command.

**Comment by kangax** [comment]
Strange, I thought we haven't had any simplify changes since the latest release?

**Comment by boopathi** [comment]
This throws in the REPL. but when I try this locally, it doesn't throw.

**Comment by kangax** [comment]
We need to update REPL

**Comment by boopathi** [comment]
Doesn't throw anymore.
