### ISSUE TITLE
Object initialization is dropped

### ISSUE THREAD

**Issue by kangax** [babel/babili#258]
```js
if (typeof x == "undefined") var x = { };
if (typeof x.y == "undefined") x.y = { };

module.exports = x;
```

becomes:

```js
var x;"undefined"==typeof x.y&&(x.y={}),module.exports=x;
```

This errors out due to `x` being `undefined` rather than an object, which it should have been initialized to.

**Comment by boopathi** [comment]
Upstream bug: babel/babel#4420

Example: http://astexplorer.net/#/Hm1Ygglqbn

**Comment by boopathi** [comment]
https://github.com/babel/babel/pull/4875

**Comment by boopathi** [comment]
https://github.com/babel/babel/pull/4875 is merged and already released and this is not an issue anymore.
