### ISSUE TITLE
Babili LICENSE file should include Uglify license

### ISSUE THREAD

**Issue by kzc** [babel/babili#259]
https://github.com/babel/babili/commit/fd640d10d0f9c36d6e5c57510e2bf3c09fe8e96f#commitcomment-19740712

**Comment by hzoo** [comment]
Ah thanks. We should be able to add a license header to the test file then?

**Comment by kzc** [comment]
I didn't examine all the test files for other Uglify tests. But if that's the only one, sure.

**Comment by kzc** [comment]
@kangax How was this issue resolved?

I don't see #260 committed to master.

**Comment by kangax** [comment]
It was commited in https://github.com/babel/babili/commit/4f00086aecab37dc2d7f94f1c67d8c6f30785831

Not sure what's the point of #260?

**Comment by kzc** [comment]
Will the license-0 branch be merged to master?

**Comment by kangax** [comment]
@boopathi I'm confused. What's the difference btw 259 and 260?

**Comment by kzc** [comment]
compare

https://github.com/babel/babili/commits/license-0

to

https://github.com/babel/babili/commits/master

**Comment by kangax** [comment]
Hm, I merged #260. Sorry for the confusion everyone and thanks for catching that @kzc
