### ISSUE TITLE
minify-dead-code-elimination incorrectly removes return statement in a loop

### ISSUE THREAD

**Issue by asapach** [babel/babili#275]
Simplified repro:
```js
function remove(id) {
    for (var j = 0; j < array.length; ++j) {
        if (array[j] === id) {
            array.splice(j, 1);
            return;
        }
    }
}
```
Output:
```js
function remove(id) {
    for (var j = 0; j < array.length; ++j) {
        if (array[j] === id) {
            array.splice(j, 1);
        }
    }
}
```
In this case `return` is not dead code, since it terminates the loop. Interestingly `break` statement is not removed in the similar case.
[REPL link](https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=&experimental=true&loose=true&spec=true&code=function%20remove(id)%20%7B%0A%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20array.length%3B%20%2B%2Bj)%20%7B%0A%20%20%20%20%20%20%20%20if%20(array%5Bj%5D%20%3D%3D%3D%20id)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20array.splice(j%2C%201)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A)

**Comment by boopathi** [comment]
#266 fixes it
