### ISSUE TITLE
NFE name is not removed w. es2015 preset

### ISSUE THREAD

**Issue by kangax** [babel/babili#289]
```js
> babel.transform('var x = { y: function y() {} }', { presets: ['babili'] }).code
'var x={y:function(){}};'
> babel.transform('var x = { y: function y() {} }', { presets: ['babili', 'es2015'] }).code
'"use strict";var x={y:function y(){}};'
```

Why did we leave `y` in the 2nd case?

**Comment by vigneshshanmugam** [comment]
@kangax I will take it :)

**Comment by vigneshshanmugam** [comment]
The problem here is.. 

[babel-plugin-transform-es2015-function-name](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-function-name) plugin in the es2015 preset adds the function name again to the output.

**Comment by kangax** [comment]
Ahh.. ok so this works for me. This is a non-issue then.

```js
> require('babel-core').transform('var x = { y: function y() {} }', { presets: ['es2015', 'babili'], passPerPreset: true }).code;
```

**Comment by vigneshshanmugam** [comment]
@kangax i sent a PR anyway to fix this issue.
