### ISSUE TITLE
Lift var declarations to the loop initializer

### ISSUE THREAD

**Issue by kangax** [babel/babili#290]
Currently, this code:

```js
for (var i = 0; i < 0; i++) {
  var j = jj();
  console.log(j);
}
```
transforms to:
```js
for(var i=0;0>i;i++){var j=jj();console.log(j)}
```
but if we lift var declarations to the loop, we can get it down to:
```js
for(var i=0,j;0>i;i++){j=jj();console.log(j)}
```

This becomes irrelevant with multiple declarations so we might only consider doing this in certain cases but not others:

```js
for (var i = 0; i < 0; i++) {
  var j = jj(), k = kk(), l = ll();
  console.log(j, k, l);
}
```
transforms to:
```js
for(var i=0;0>i;i++){var j=jj(),k=kk(),l=ll();console.log(j,k,l)}
```
and is same length with lifted:
```js
for(var i=0,j,k,l;0>i;i++){j=jj(),k=kk(),l=ll();console.log(j,k,l)}
```

**Comment by boopathi** [comment]
```js
for(var i=0;;){var j=foo;}
for(var i=0,j;;){j=foo;}

for(var i=0;;){var j=foo, k=bar;}
for(var i=0,j,k;;){j=foo, k=bar;}

// and we can stop at 2
for(var i=0;;){var j=foo, k=bar, l=baz;}
for(var i=0,j,k,l;;){j=foo, k=bar, l=baz;}
```

The gotcha I see here is the order of transformations.

```js
for (var i = 0;;) { var j = foo; var k = bar; }
```

`merging sibling variables` vs `hoisting to previous for-loop`.

**Comment by boopathi** [comment]
We can do this as a part of merging-sibling-variables only ... and not worry about order. !!!

**Comment by vigneshshanmugam** [comment]
@kangax @boopathi I will work on this if you guys are okay with it :)

**Comment by kangax** [comment]
@vigneshshanmugam sure, any help is welcome!
