### ISSUE TITLE
Error w. JSX element in certain context

### ISSUE THREAD

**Issue by kangax** [babel/babili#301]
Getting this error:

_Property name of JSXOpeningElement expected node to be of a type ["JSXIdentifier","JSXMemberExpression"] but instead got "Identifier"_

for this code:

```js
async function f() {
  await Promise.all(
    async () => {
      const {x} = y;
      const X = x;
      return <X />;
    }
  )
}
```

Repl:

https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=async%20function%20f()%20%7B%0A%20%20await%20Promise.all(%0A%20%20%20%20async%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20const%20%7Bx%7D%20%3D%20y%3B%0A%20%20%20%20%20%20const%20X%20%3D%20x%3B%0A%20%20%20%20%20%20return%20%3CX%20%2F%3E%3B%0A%20%20%20%20%7D%0A%20%20)%0A%7D

**Comment by kangax** [comment]
fwiw, this is from Nuclide's codebase — https://github.com/facebook/nuclide/blob/master/pkg/nuclide-datatip/lib/DatatipManager.js#L115

**Comment by boopathi** [comment]
A shorter version without JSX - 

```js
function f() {
  const {x} = y;
  const X = x;
  return X;
}

// output =>
function f() { return a; }

// set mergeVars:false in preset and the output is
function f() {
  const {x:a} = y;
  return a;
}
```

It's so weird that this is a bug with merge-vars and dead-code already handles this.
