### ISSUE TITLE
Using babili with ES2015 transforms and a super class breaks code

### ISSUE THREAD

**Issue by kenzierocks** [babel/babili#305]
With `babel-preset-es2015@6.18.0` and `babili@0.0.9`, the following code breaks:
```javascript
class AClass extends SomeClass {
    constructor() {
        super("some arg");
        this.func(this.val = "some value");
        this.val.someProperty = "some value";
    }
}
```
This seems to be related to the `super` call, as without it (and the `extends SomeClass`) everything is fine.

Here's a gist with the two different files I gave to Babel, and the output: https://gist.github.com/kenzierocks/4e198af6c75f359dc6ffffcfc62b1861

My `.babelrc`:
```json
{ "presets": ["es2015","babili"] }
```

**Comment by boopathi** [comment]
Related #189 (probably).

**Comment by boopathi** [comment]
Also, sending `passPerPreset: true` works. 

Anyway, I will debug more regarding this.

**Comment by kenzierocks** [comment]
Ah yea, looks like the same. I'll close in favor of that one.
