### ISSUE TITLE
babel-plugin-minify-simplify breaks logical order

### ISSUE THREAD

**Issue by mavericken** [babel/babili#312]
I illustrated it here with a comparison of the beautified outputs with and without simplify.
![image](https://cloud.githubusercontent.com/assets/7833752/20806226/01651774-b7c8-11e6-9083-ea9defd58878.png)

**Comment by boopathi** [comment]
I guess this is related to #305 . Can you try babili with `passPerPreset: true`.

From next version of babili, this option will be enabled by default for babili plugins.

**Comment by mavericken** [comment]
Looks like that works.  What if I still wanted to pick and choose individual babili plugins?  Does this mean that I would need to package my selection up into a preset so that I could make use of the passPerPreset option?

**Comment by boopathi** [comment]
Next version will have options with which you can enable/disable specific plugins - https://github.com/babel/babili/tree/master/packages/babel-preset-babili#options

**Comment by mavericken** [comment]
Turns out it didn't work.  I noticed the same problem return this morning, so I think I made some sort of mistake when testing the fix, such that it was still using an older configuration with the simplify plugin removed.

**Comment by kangax** [comment]
@mavericken could you please paste an actual code (preferably as minimal as possible) that still has an issue with `passPerPreset: true`. Otherwise, we can't test it and figure out what exactly is wrong, or even confirm it in the first place.

**Comment by mavericken** [comment]
I included babel-plugin-minify-simplify back into my project, but I can't replicate anymore.  I guess I'll close for now and reopen if I see it again.
