### ISSUE TITLE
'Return' statement dropped from 'else' clause

### ISSUE THREAD

**Issue by AshleyScirra** [babel/babili#316]
Testing with the Babel REPL set to minify with Babili.

Input:
```js
function test()
{
	while (list.length)
	{
		let lastItem = list[list.length - 1];
		
		if (lastItem.shouldRemove())
		{
			list.pop();
		}
		else
		{
			return;
		}
	}
}
```

Output, beautified:

```js
function test() {
    for (; list.length;) {
        let a = list[list.length - 1];
        a.shouldRemove() && list.pop()
    }
}
```

The `return` statement was dropped from inside the loop, which means the output code sometimes loops infinitely where the original would exit.

**Comment by boopathi** [comment]
This is already fixed in master.

**Comment by AshleyScirra** [comment]
Oh right, thanks. How often is the REPL updated? Is there somewhere I can check its version? I find it handy for quick tests and checking bugs.
