### ISSUE TITLE
Simplify after DCE requires second pass

### ISSUE THREAD

**Issue by boopathi** [babel/babili#317]
```js
function foo() {
  const a = 5;
  return a + 5;
}
```

output:
```js
function foo() {
  return 5 + 5;
}
```

Deadcode elimination is now run last, so we don't have anything after DCE. It requires a second pass to optimize this further.

**Comment by kangax** [comment]
I'm guessing we can't just swap them, right? One option could be to just run simplify again after DCE, but then we miss out on other combinations, which brings us back to #61. Should we just keep track of it there?

**Comment by boopathi** [comment]
Yeah. DCE runs on Program.exit. So order of simplify and DCE doesn't matter.

Do we have to identify the combinations (cases like this one) or would it regress if we blindly run the transformations twice (with an option) ?

Cool. Will keep track of the related issues in #61.
