### ISSUE TITLE
Optimise mangler variable name choices for compression.

### ISSUE THREAD

**Issue by bardiharborow** [babel/babili#330]
The mangler should have the ability to choose variable names that are [optimised for compression in a similar way to UglifyJS](http://lisperator.net/uglifyjs/mangle).

**Comment by boopathi** [comment]
We do that already - https://github.com/babel/babili/blob/b8bac37d02c471e2c0f7a845b8afce572870092c/packages/babel-plugin-minify-mangle-names/src/index.js#L219-L225

But mangler went through some rewrites and requires some more stuff to be fixed and improved #284 and I'll revisit that once we get these fixed.
