### ISSUE TITLE
t.isNodesEquivalent is not a function

### ISSUE THREAD

**Issue by ronag** [babel/babili#331]
I'm getting the error `t.isNodesEquivalent is not a function`

```
      new BabiliPlugin({
        comments: false,
        babili: require('babel-preset-babili')
      }),
```

```
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: [['env', { targets: { chrome: 54 } }], 'react', 'stage-0'],
          plugins: [
            'transform-decorators-legacy'
          ],
          env: {
            production: {
              presets: ['react-optimize']
            }
          }
        }
```

```

    "babel-loader": "6.2.9",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-react": "6.16.0",
    "babel-preset-react-optimize": "1.0.1",
    "babel-preset-stage-0": "6.16.0",
    "babili-webpack-plugin": "0.0.7",
```

How can I debug this?

**Comment by asapach** [comment]
https://github.com/babel/babili#requirements
* babel-core >= 6.19.0

Check your version.

**Comment by ronag** [comment]
@asapach: Does that version even exist? The latest one seems to be `6.18.2`?

**Comment by boopathi** [comment]
yeah. It's babel-types version `6.19.0`... babel-core is 6.18.2 ...

@hzoo I think the next version of babel-core should have babel-types >=6.19.0 in it's dependencies. Right now we rely on ^6.18.0 which will install 6.19.0

**Comment by kangax** [comment]
From what I understand this is a Babel issue, so I'll close this one.

**Comment by davidnagli** [comment]
I'm having the same exact issue. The error shows that it **is** coming from Babili.

**Comment by hzoo** [comment]
what happened is we moved `isNodesEquivalent` from being an internal method in babili to part of `babel-types` which is `t`. If there's a way to check if you're `babel-types` is up to date then that would be good.

**Comment by davidnagli** [comment]
@hzoo Do you have a way for me to do that?

**Comment by hzoo** [comment]
have you tried `rm -rf node_modules` and npm installing again? it should be requesting the latest babel-types?

**Comment by davidnagli** [comment]
I have it installed globally. I'll do `npm uninstall -g babel`

**Comment by hzoo** [comment]
ah interesting.. `babel` doesn't actually do anything? You should of installed babel-cli/babel-core or something

**Comment by davidnagli** [comment]
Your right... I reinstalled babel-cli and babili, it works now. Thanks
