### ISSUE TITLE
const variable renaming goes awry

### ISSUE THREAD

**Issue by Moeriki** [babel/babili#333]
[REPL](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015&code=(()%20%3D%3E%20%7B%0A%20%20if%20(!window)%20%7B%0A%20%20%20%20return%3B%0A%20%20%7D%0A%0A%20%20const%20iframe%20%3D%20document.getElementById('iframe')%3B%0A%20%20const%20win%20%3D%20iframe.window%3B%0A%0A%20%20function%20bootstrap()%20%7B%0A%20%20%20%20win.getElementById('test')%3B%0A%20%20%7D%0A%0A%20%20if%20(!window)%20%7B%0A%20%20%20%20bootstrap()%3B%0A%20%20%7D%0A%7D)()%3B%0A)

Required presets: es2015, babili

```javascript
(() => {
  if (!window) {
    return;
  }

  const iframe = document.getElementById('iframe');
  const win = iframe.window;

  function bootstrap() {
    win.getElementById('test');
  }

  if (!window) {
    bootstrap();
  }
})();
```

⬇️

```javascript
(function() {
    function a() {
        c.getElementById('test') // c does not exist
    }
    if (window) {
        var _b = document.getElementById('iframe'),
            _c = _b.window;
        window || a()
    }
})();
```

**Comment by boopathi** [comment]
When I run it in my local with es2015, babili as presets, I don't get the `_b` and `_c` as the names ... I get `b` and `c` as the var names. On the repl though, this bug appears.

**Comment by Moeriki** [comment]
My versions.

```json
{
    "babel-cli": "~6.18.0",
    "babel-core": "~6.20.0",
    "babel-preset-babili": "0.0.9",
    "babel-preset-es2015": "~6.18.0"
}
```

My command.

```
babel test.js --presets=es2015,babili
```

**Comment by Moeriki** [comment]
When I make `iframe` and `win` var instead of const, there is no issue.

**Comment by Moeriki** [comment]
Weird. This also works fine.

```
babel test.js --presets=es2015 | babel --presets=babili              
```

**Comment by kangax** [comment]
I'm closing since REPL version is quite outdated and I'll try to update it today.
