### ISSUE TITLE
Empty lines and newlines not stripped

### ISSUE THREAD

**Issue by FezVrasta** [babel/babili#342]
So, I'm trying to replace uglify with babili in my popper.js.org project ([v1-dev-babili](https://github.com/FezVrasta/popper.js/tree/v1-dev-babili) branch).

This is the result when I try to minify the source code:

https://gist.github.com/FezVrasta/16c5d5e5ff1211922ddcf090c8454d74

As you can see, lot of stuff get minified, but starting from line 87, seems like the minification does nothing.

Also, why there are so much empty lines and the strippable newlines aren't stripped?

**Comment by kangax** [comment]
https://github.com/FezVrasta/popper.js/commit/100fa8a273a17aa3cc54231c1e3e812c84b21441#diff-35b4a816e0441e6a375cd925af50752cR14

**Comment by FezVrasta** [comment]
ah, it's not mentioned in the readme, I thought the only purpose of this library was to minfy stuff, I would never thought I had to ask it explicitly.

Thank you for the info

**Comment by FezVrasta** [comment]
I tried your suggestion but the result is the same...

You can find the updated rollup + babel config here:
https://github.com/FezVrasta/popper.js/blob/v1-dev/scripts/rollup.config.min.js

**Comment by kangax** [comment]
Have you checked if it's related to rollup and/or its plugin? This definitely works (comments: false, compact: true, etc.) in a standalone configuration.

**Comment by FezVrasta** [comment]
the other options of babel work, babili does something, but not everything... (it minifies just some parts of the file).

I doubt it's rollup's fault.

**Comment by kangax** [comment]
Can you try running that file through Babili (from node or console) and see if still happens? Then we know it's us.

**Comment by FezVrasta** [comment]
Yea, seems like babili isn't executed properly inside Rollup, probably it gets executed for each file instead on the finished bundle. Thanks for the info!

**Comment by kangax** [comment]
Sure thing, glad we figured it out.

**Comment by frontools** [comment]
Not sure it's a rollup issue. It doesn't work with browserify too.

**Comment by FezVrasta** [comment]
To make it work with Rollup, I had to use babili alone via CLI:

https://github.com/FezVrasta/popper.js/blob/v1-dev/package.json#L15

**Comment by Haroenv** [comment]
I didn't get this working either with rollup, it minified my own code, but not the parts written by babel. 

[gist](https://gist.github.com/Haroenv/1bbd6d7407a27a4a42a2e0d61cdf5aa1)

maybe the order it's doing the transforms in isn't correct with rollup-plugin-babel or something like that? 

[holmes](https://github.com/Haroenv/holmes) is where I tried it

**Comment by boopathi** [comment]
I tried babili with rollup-plugin-babel - replacing `es2015-rollup` preset to `es2015` preset (with the option `{ modules: false }` - es2015-rollup is the same thing - right? ), it seems to remove the new lines created as a result of es2015 transform injections (like classCallCheck etc...). 

But there are a few more new lines - I guess this is because rollup now generates the final output.

**Comment by FezVrasta** [comment]
Try [`rollup-plugin-real-babili`](https://www.npmjs.com/package/rollup-plugin-real-babili)
