### ISSUE TITLE
"do expressions" are incorrectly minified

### ISSUE THREAD

**Issue by Daniel15** [babel/babili#350]
See https://babeljs.io/docs/plugins/transform-do-expressions/

Note: You need to explicitly enable the transform, or use the `stage-0` preset.

Example input:
```js
var foo = do {
  if (aaa) {
    'a';
  } else {
    'b';
  }
}
console.log(foo);
```

Example Babel output:
```js
'use strict';

var foo = aaa ? 'a' : 'b';
console.log(foo);
```

Example Babili output:
```js
'use strict';var foo=(aaa,void 0);console.log(foo);
```
(notice `'a'` and `'b'` disappear)

Example of the output I'd expect from Babili:
```js
'use strict';var foo=aaa?'a':'b';console.log(foo);
```

**Comment by bardiharborow** [comment]
It sounds like Babili is running before the `transform-do-expressions` plugin, rather than after.

**Comment by kangax** [comment]
This is the usual `passPerPreset=false` issue (just verified locally). Since we enable it by default in a preset now, I'm closing. Thanks for the report @Daniel15
