### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by hzoo** [babel/babili#36]
Ref https://github.com/amasad/babel-minify/pull/33#issuecomment-229204819

The benchmarks are cool, but we could reduce the size and find out we are breaking the functionality (especially for the dead code elimination plugin).

So we could be running the unit tests of the project on the minified code?

**Comment by boopathi** [comment]
We have Smoke tests(#492) now that runs against 3 libraries (lodash, html-minifier, jquery) running all it's tests on the babilified code. Will re-open this if there are more ideas and requirements.

**Comment by amasad** [comment]
@boopathi did you consider running test262?

**Comment by boopathi** [comment]
Yes. Have to try it out. Do you think we should we re-open this for test262?

**Comment by amasad** [comment]
or some other issue, eitherways
