### ISSUE TITLE
[babel-preset-babili 0.0.9] Confusion/bug eliminating unreachable code that uses require

### ISSUE THREAD

**Issue by avaragado** [babel/babili#361]
I'm building an app using electron 1.4.13. I'm using babel-preset-env to target babel to the current node release (7.3.0) for transpilation of electron's main process code. (Main process code doesn't need to be bundled into a single file and can use require.)

In the main process code, I want to use NODE_ENV to include/exclude code based on the build target. I see there are two ways to do this: babel-plugin-transform-node-env-inline and babel-plugin-transform-inline-environment-variables.

(I'm not sure why there are two methods. This is a side issue, but a point of confusion.)

I'm seeing a problem using either method: code that should be removed as unreachable is left in the source if it contains `require`.

The `.babelrc` in use (here with babel-plugin-transform-node-env-inline):

```json
{
    "presets": [
        [
            "env",
            {
                "targets": {
                    "node": "current"
                }
            }
        ]
    ],
    "plugins": [
        "transform-node-env-inline"
    ],
    "env": {
        "production": {
            "presets": ["babili"]
        }
    }
}
```

Build method (`ttt` is a temp test directory): 

`NODE_ENV=production babel src/ttt --out-dir out/ttt`

Test file `src/ttt/ttt.js` (the `require`d file exists):

```js
console.log('pre');

if (false) {
    const ccc = require('../../config');
    console.log(`1 ${ccc}`);
}

if ('x' !== 'x') {
    const ccc = require('../../config');
    console.log(`2 ${ccc}`);
}

if (process.env.NODE_ENV === 'x') {
    const ccc = require('../../config');
    console.log(`3 ${ccc}`);
}

if (process.env.NODE_ENV === 'x') {
    console.log('4');
}

console.log('post');
```

Since every test is false, with either inlining plugin I expect to see `"use strict"` plus two `console.log` calls for "pre" and "post".

Actual output (with babel-plugin-transform-node-env-inline), reformatted for readability:

```js
'use strict';
if (console.log('pre'), !1) {
  const a = require('../../config');
  console.log(`3 ${a}`)
}
!1, console.log('post');
```

With babel-plugin-transform-inline-environment-variables instead:

```js
'use strict';
if (console.log('pre'), 'x' === 'production') {
  const a = require('../../config');
  console.log(`3 ${a}`)
}
!1, console.log('post');
```

Am I doing anything wrong?

**Comment by boopathi** [comment]
This is fixed in #386 .
