### ISSUE TITLE
Create aliases for built in functions

### ISSUE THREAD

**Issue by FezVrasta** [babel/babili#363]
I mean, if I use multiple times `Math.floor`, it would make sense to assign it to a variable and use the variable. 

```
function(x, y,z) {
  return { Math.floor(x), Math.floor(y), Math.floor(z)  };
}
```

To

```
function(x, y, z) {
  let a = Math.floor;
  return { a(x), a(y), a(z) };
}
```

**Comment by kangax** [comment]
We can do that if we know that a function call is idempotent (i.e. has no side effects). In this case, `Math.floor` is a getter but if this was `doSomethingDestructive(x) + doSomethingDestructive(y)` then we go from a side effect that happens twice to a side effect that happens once, which changes behavior.

We can maintain our own list of pure functions and/or allow for specifying a whitelist via options.

**Comment by FezVrasta** [comment]
Why you say so? You would alias the function before it's executed.

so:
```
let a = doSomethingDestructive;
a(x) + a(y)
```

The result would be the same.

**Comment by kangax** [comment]
Oh, you're right. I was thinking of getters (when `foo.bar` evaluation has a side effect). This should be safer to implement then, as long as safeGetters option is enabled.

**Comment by vigneshshanmugam** [comment]
Gonna try it out. @kangax @boopathi
