### ISSUE TITLE
Mangler using wrong variable name in some cases

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babili#369]
Tested out the mangler on our codebase and got the following:
```
function decodeMessage(message){
    let namespace;
    let name;
    let value = null;

    [, namespace, name, value] = message.split(',') || [];
    console.log(name);
}
```

converts to

    function decodeMessage(a) {
        let b;
        let c;
        let d = null;

        [ , b , d , d ] = a.split(',') || [];
        console.log(c);
    }

notice the third item in the destructured array is `d` instead of `c` for some reason.

I see there are a few mangler bugs filed, but I don't know if this is one of them. Sorry if it is a duplicate.

**Comment by boopathi** [comment]
Related #326

**Comment by filmic** [comment]
Similar issue with broken array destructuring:

```
function currentData(id) {
	let [alpha, beta, gamma] = id.split('_');
	[alpha, beta, gamma] = _.map([alpha, beta, gamma], idPart => {
		return parseInt(idPart, 10);
	});
}
```
is converted to:

```
function currentData(a){let[b,c,d]=a.split('_');[b,d,d]=_.map([b,c,d],e=>{return parseInt(e,10)})}
```
[REPL LINK](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=true&presets=stage-2&code=function%20currentData(id)%20%7B%0A%09%09let%20%5Balpha%2C%20beta%2C%20gamma%5D%20%3D%20id.split('_')%3B%0A%0A%09%09%5Balpha%2C%20beta%2C%20gamma%5D%20%3D%20_.map(%5Balpha%2C%20beta%2C%20gamma%5D%2C%20idPart%20%3D%3E%20%7B%0A%09%09%09return%20parseInt(idPart%2C%2010)%3B%0A%09%09%7D)%3B%0A%09%09%0A%09%09console.log(alpha)%3B%0A%09%09console.log(beta)%3B%20%2F%2F%20beta%20should%20be%202%20but%20logs%20as%20%222%22%0A%09%09console.log(gamma)%3B%0A%7D%0A%0AcurrentData('1_2_3')%3B)

**Comment by keithamus** [comment]
I also have a similar issue, but this is with destructuring in function arguments. Was unsure if I should file a new issue or put it in this one.

## Given:

```jsx
const Main = ({ thing: Thing = 'div' }) => <Thing />;
<Main thing={'span'} />
```

## Actual (formatted)
```jsx
const Main=({thing:a='div'})=>React.createElement(Thing,null); // ReferenceError Thing is not defined
React.createElement(Main,{thing:'span'});
```

## Expected (formatted)
```jsx
const Main=({thing:a='div'})=>React.createElement(a,null); // ReferenceError Thing is not defined
React.createElement(Main,{thing:'span'});
```

**Comment by xtuc** [comment]
@keithamus I think this is correct because you shoud write that:
```js
const Main = ({ Thing: ThingInterface = 'div' }) => <Thing />;
<Main thing={'span'} />
```

The `thing` variable must be in uppercase. You are 'using' the type insteand of the variable.

**Comment by keithamus** [comment]
You're right @xtuc, I've updated my expected to reflect that. The salient point, however, is that the name is mangled but this is not reflected into the rest of the function
