### ISSUE TITLE
`new RegExp` broken with concat unicode string

### ISSUE THREAD

**Issue by jhen0409** [babel/babili#370]
[REPL link](http://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=react%2Cstage-2&code=var%20ws%20%3D%20'%5Cx09%5Cx0A%5Cx0B%5Cx0C%5Cx0D%5Cx20%5CxA0%5Cu1680%5Cu180E%5Cu2000%5Cu2001%5Cu2002%5Cu2003'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20'%5Cu2004%5Cu2005%5Cu2006%5Cu2007%5Cu2008%5Cu2009%5Cu200A%5Cu202F%5Cu205F%5Cu3000%5Cu2028'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20'%5Cu2029%5CuFEFF'%3B%0Anew%20RegExp('%5E%5B'%20%2B%20ws%20%2B%20'%5D%5B'%20%2B%20ws%20%2B%20'%5D*')%0A)

```js
var ws = '\x09\x0A\x0B\x0C\x0D\x20\xA0\u1680\u180E\u2000\u2001\u2002\u2003' +
           '\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u202F\u205F\u3000\u2028' +
           '\u2029\uFEFF';
new RegExp('^[' + ws + '][' + ws + ']*')
```

Run the output on console, will throw the error:

```
Uncaught SyntaxError: Invalid regular expression: missing /
```

I got this problem from https://github.com/jhen0409/react-native-debugger/pull/35, it bundled  [ramda/src/trim.js](https://github.com/ramda/ramda/blob/50758266f8afb18c38bc2de9a12a8a4bf9707b72/src/trim.js).

**Comment by jhen0409** [comment]
Looks like it has been fixed by #304, any news for release?

**Comment by boopathi** [comment]
It's released
