### ISSUE TITLE
babel-plugin-minify-dead-code-elimination `SequenceExpression` use case

### ISSUE THREAD

**Issue by jtenner** [babel/babili#373]
`SequenceExpression` in `ExpressionStatement` containing `UnaryExpression(void 0)` does not remove dead code.

I realize this is a small use case, but if an `ExpressionStatement` contains a `SequenceExpression` with void 0 it can be removed with no worry of side-effects.

```javascript
  a, b, c, d, void 0;
```

should be:
```javascript
  a, b, c, d;
```

Thanks for reading!

-Josh

**Comment by kangax** [comment]
Thanks for reporting, definitely a valid use case.

**Comment by jtenner** [comment]
Thanks for replying!  I don't suppose I can help?

**Comment by boopathi** [comment]
It's an unsafe transformation - 

```js
function f1() {
  return 1, 2, void 0;
}

function f2() {
  return 1, 2;
}

console.log(f1(), f2()); // will print undefined, 2
```

**Comment by jtenner** [comment]
@boopathi when the parent is an ExpressionStatement it is completely safe.

Also when the sequence expression contains void 0 and it's not the last item it is safe too.

```javascript
//Any other statement with an expression that contains a sequence expression
let g = (void 0, void 0, 1);

//ExpressionStatement (SequenceExpression)
void 0, 1, 2, 3,;



```

**Comment by jtenner** [comment]
Example visitor that might be useful.

Check out this [example](https://astexplorer.net/#/uCLvkAq8j9) here. It should be correct.

For some reason the transformation yields two sequence expressions but the general idea here is that some `void 0` operations are definitely ignored and we can easily determine if it is safe to ignore them.

**Comment by kangax** [comment]
This is similar to https://github.com/babel/babili/pull/197/files where we remove undefined only when it's in a "safe" context.

**Comment by jtenner** [comment]
Thanks guys!  This is really awesome.

**Comment by jtenner** [comment]
@kangax do you detect to see if `undefined` is overwritten?  It's possible it might be unsafe, unlike `void 0`.

**Comment by kangax** [comment]
You're right, it's unsafe. I looked into fixing it in Babili, then realized it has to do with Babel's `path.evaluate()` incorrectly thinking that `undefined` is `undefined`. Filed a bug — https://github.com/babel/babel/issues/5204
