### ISSUE TITLE
Remainder operator (%) use broken

### ISSUE THREAD

**Issue by filmic** [babel/babili#377]
Code using remainder operator (%) is incorrectly minified in that case:

input:
```
function calc(str) { 
  let a = parseInt(str, 10)
  a = a - a % 10;
  return a;
}
```

output:
```
function calc(b){
var c=parseInt(b,10);
return c%=10,c
}
```

Calling function `calc('109')` returns `9` but should return `100` 
[REPL link](http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015%2Cstage-2&experimental=false&loose=false&spec=false&code=function%20calc(str)%20%7B%20%0A%20%20let%20a%20%3D%20parseInt(str%2C%2010)%0A%20%20a%20%3D%20a%20-%20a%20%25%2010%3B%0A%20%20return%20a%3B%0A%7D%0A%0A%0Aconsole.log(calc('109'))%3B%20%2F%2F%20should%20log%20100%20but%20logs%209)

Error exists when using `babel-preset-babili@0.0.9` (`0.0.8` is working correct).

**Comment by kangax** [comment]
Can you please give an example?

**Comment by goto-bus-stop** [comment]
This was indeed broken in 0.0.9:

    ➜  babili git:(babili@0.0.9) echo 'a = a - a % 10' | babel --presets ./packages/babel-preset-babili
    a%=10;

But looks like it's fixed on master:

    ➜  babili git:(master) echo 'a = a - a % 10' | babel --presets ./packages/babel-preset-babili
    a-=a%10;

**Comment by filmic** [comment]
@kangax Example and REPL link are provided in the issue description above.

**Comment by kangax** [comment]
This is fixed on master. I'm making a release right now.
