### ISSUE TITLE
Bug in deconstruction minification

### ISSUE THREAD

**Issue by Reinmar** [babel/babili#397]
I've been testing how Babili works with [CKEditor 5](https://github.com/ckeditor/ckeditor5) and I encountered a bug with swapped variable names.

I tried to debug it and the smallest possible scenario is minifying this function: https://github.com/ckeditor/ckeditor5-utils/blob/d3702f4d396849ab3e67358ef74fb670133b4e89/src/dom/position.js#L78-L113

If you pass it through Babili (see on [REPL](https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=true&presets=&targets=&browsers=&builtIns=false&experimental=true&loose=false&spec=false&code=export%20function%20getOptimalPosition(%20%7B%20element%2C%20target%2C%20positions%2C%20limiter%2C%20fitInViewport%20%7D%20)%20%7B%0A%09const%20positionedElementAncestor%20%3D%20getPositionedAncestor(%20element.parentElement%20)%3B%0A%09const%20elementRect%20%3D%20new%20Rect(%20element%20)%3B%0A%09const%20targetRect%20%3D%20new%20Rect(%20target%20)%3B%0A%0A%09let%20bestPosition%3B%0A%09let%20name%3B%0A%0A%09%2F%2F%20If%20there%20are%20no%20limits%2C%20just%20grab%20the%20very%20first%20position%20and%20be%20done%20with%20that%20drama.%0A%09if%20(%20!limiter%20%26%26%20!fitInViewport%20)%20%7B%0A%09%09%5B%20name%2C%20bestPosition%20%5D%20%3D%20getPosition(%20positions%5B%200%20%5D%2C%20targetRect%2C%20elementRect%20)%3B%0A%09%7D%20else%20%7B%0A%09%09const%20limiterRect%20%3D%20limiter%20%26%26%20new%20Rect(%20limiter%20)%3B%0A%09%09const%20viewportRect%20%3D%20fitInViewport%20%26%26%20Rect.getViewportRect()%3B%0A%0A%09%09%5B%20name%2C%20bestPosition%20%5D%20%3D%0A%09%09%09getBestPosition(%20positions%2C%20targetRect%2C%20elementRect%2C%20limiterRect%2C%20viewportRect%20)%20%7C%7C%0A%09%09%09%2F%2F%20If%20there's%20no%20best%20position%20found%2C%20i.e.%20when%20all%20intersections%20have%20no%20area%20because%0A%09%09%09%2F%2F%20rects%20have%20no%20width%20or%20height%2C%20then%20just%20use%20the%20first%20available%20position.%0A%09%09%09getPosition(%20positions%5B%200%20%5D%2C%20targetRect%2C%20elementRect%20)%3B%0A%09%7D%0A%0A%09let%20%7B%20left%2C%20top%20%7D%20%3D%20getAbsoluteRectCoordinates(%20bestPosition%20)%3B%0A%0A%09%2F%2F%20(%23126)%20If%20there's%20some%20positioned%20ancestor%20of%20the%20panel%2C%20then%20its%20rect%20must%20be%20taken%20into%0A%09%2F%2F%20consideration.%20%60Rect%60%20is%20always%20relative%20to%20the%20viewport%20while%20%60position%3A%20absolute%60%20works%0A%09%2F%2F%20with%20respect%20to%20that%20positioned%20ancestor.%0A%09if%20(%20positionedElementAncestor%20)%20%7B%0A%09%09const%20ancestorPosition%20%3D%20getAbsoluteRectCoordinates(%20new%20Rect(%20positionedElementAncestor%20)%20)%3B%0A%0A%09%09left%20-%3D%20ancestorPosition.left%3B%0A%09%09top%20-%3D%20ancestorPosition.top%3B%0A%09%7D%0A%0A%09return%20%7B%20left%2C%20top%2C%20name%20%7D%3B%0A%7D)) the `name` property in the return value is set to `bestPosition` from line 93.

We had this:

```js
[ name, bestPosition ] =
getBestPosition( positions, targetRect, elementRect, limiterRect, viewportRect ) 

// ...

return { left, top, name };
```

And we get this:

```js
[i,j]=getBestPosition(c,h,g,m,n)

// ...

return{left:k,top:l,name:j}
```

**Comment by Reinmar** [comment]
Fun fact, if you swap variable definitions to:

```js
	let name;
	let bestPosition;
```

everything is ok.

**Comment by boopathi** [comment]
Related #326, #369. #390 fixes it and is already merged to master.
