### ISSUE TITLE
If..return removes something it shouldn't

### ISSUE THREAD

**Issue by zaygraveyard** [babel/babili#399]
```jsx
(function listSnaps(snapsList) {
  if (!snapsList) {
    return;
  }

  let pendingIdText = '';

  function handleData(newText: string) {
    const snapIds = (pendingIdText + newText).split(',');

    pendingIdText = snapIds.pop();
    console.log(snapIds);
  }
  handleData('a,b');
}(true));
```
Results in
```js
(function(b){function c(e){const f=(d+e).split(',');d=f.pop(),console.log(f)}if(b){c('a,b')}})(!0);
```
Which gives **"d is not defined"**.
`pendingIdText` became `d` but the `let pendingIdText = '';` was removed!

[try it](http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=react%2Cstage-2&targets=&browsers=&builtIns=false&code=(function%20listSnaps(snapsList)%20%7B%0A%20%20if%20(!snapsList)%20%7B%0A%20%20%20%20return%3B%0A%20%20%7D%0A%0A%20%20let%20pendingIdText%20%3D%20''%3B%0A%0A%20%20function%20handleData(newText%3A%20string)%20%7B%0A%20%20%20%20const%20snapIds%20%3D%20(pendingIdText%20%2B%20newText).split('%2C')%3B%0A%0A%20%20%20%20pendingIdText%20%3D%20snapIds.pop()%3B%0A%20%20%20%20console.log(snapIds)%3B%0A%20%20%7D%0A%20%20handleData('a%2Cb')%3B%0A%7D(true))%3B)

**Comment by boopathi** [comment]
Some bug with if..return in DCE.

**Comment by boopathi** [comment]
Related #281

**Comment by boopathi** [comment]
Fix for #281 and fix for this one feels like 

![](http://i.imgur.com/ZyzGOHu.gif)

**Comment by boopathi** [comment]
/cc @kangax @hzoo 

Need some suggestions to handle this - 

```js
function a() {
  if (foo) return;
  let x = 1;
  function b() { use(x); }
}
```

cannot be transformed to 

```js
function a() {
  function b() { use(x); }
  if (!foo) {
    let x = 1;
  }
}
```

Options are 

+ Detect block scoped binding usages and deopt if_return transformation (since this transformation itself causes changes in block, and we have a babel issue with bindings and scopes, it MIGHT lead to other issues with bindings or detection)
+ Hoist `let` declaration: Cannot have `const`, and also here, we'll suppress a possible error by doing this as `let` is not hoisted. 

```js
function a() {
  if (foo) return;
  use(x); // here it will throw as x is not yet a binding and let is not hoisted
  let x = 1;
  function b() { use(x) };
}
```

to

```js
function a() {
  function b() { use(x); }
  let x;
  if (!foo) {
    use(x); // here x is a binding and is undefined
    x = 1;
  }
}
```

Any other ideas or suggestions welcome.

**Comment by zaygraveyard** [comment]
@boopathi Why not wrap the whole thing with the `if`?
```js
function a() {
  if (!foo) {
    let x = 1;
    function b() { use(x); }
  }
}
```

**Comment by boopathi** [comment]
@zaygraveyard 

```js
function a() {
  if (b()) { // error
    function b() {} // let binding & hoisted within the block
  }
}
```

**Comment by hzoo** [comment]
I think it's best for us to deopt when possible and then go back and do optimizations? I think our goal is stability first, opt later?

**Comment by boopathi** [comment]
@hzoo True. But the only thing that's blocking is some bugs babel's scope tracking - we solved most of these issues (in mangler and dce) - by doing `traverse.clearCache()` and `scope.crawl()`. We cannot do that in `simplify`, and we don't want simply to be a single pass.
