### ISSUE TITLE
Runtime error after minifying the react-redux library 

### ISSUE THREAD

**Issue by galenus** [babel/babili#405]
Using the babili through babili-webpack-plugin and through CLI results in runtime error in minified version of the react-redux library: *TypeError: Cannot call a class as a function*.
This is inside `Provider` constructor. 
A project reproducing the error can be found [here](https://github.com/galenus/babili-react-redux-bug).

**Comment by boopathi** [comment]
Do you have a minimal repro snippet? Will be easier to spot the bug.

**Comment by galenus** [comment]
See the index.tsx inside the linked repository. It's very minimal.

**Comment by vigneshshanmugam** [comment]
@galenus This is already fixed in master. Verified the same using your repo.

**Comment by galenus** [comment]
@vigneshshanmugam what library should I take for this to work?

**Comment by vigneshshanmugam** [comment]
@galenus I tried in latest babili master.. It will be released today

**Comment by galenus** [comment]
@vigneshshanmugam yes, but what package exactly? I am consuming babili through the webpack plugin, so I'd like to update only the necessary dependencies, if it's possible.

**Comment by vigneshshanmugam** [comment]
@galenus No its not possible.. babili-webpack depends on babel-preset-babili so you need to wait till a new version of babili is published https://github.com/boopathi/babili-webpack-plugin/blob/master/package.json#L24
