### ISSUE TITLE
Invalid string concatenation breaks Lodash _.template method

### ISSUE THREAD

**Issue by filmic** [babel/babili#413]
Minifing the Lodash library using Babili 0.0.11 breaks the `_.template` method.

The string concatenation in that method (https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L14748) is minified to contain extraneous escape characters.

Input:
```
source = 'function(' + (variable || 'obj') + ') {\n' +
        (variable
          ? ''
          : 'obj || (obj = {});\n'
        ) +
        "var __t, __p = ''" +
        (isEscaping
           ? ', __e = _.escape'
           : ''
        ) +
        (isEvaluating
          ? ', __j = Array.prototype.join;\n' +
            "function print() { __p += __j.call(arguments, '') }\n"
          : ';\n'
        ) +
        source +
        'return __p\n}';
```

Output:
`source='function('+(variable||'obj')+') {\n'+(variable?'':'obj || (obj = {});\n')+'var __t, __p = \'\''+(isEscaping?', __e = _.escape':'')+(isEvaluating?', __j = Array.prototype.join;\\nfunction print() { __p += __j.call(arguments, \\\'\\\') }\\n':';\n')+source+'return __p\n}';`

Notice extra escape in `\\n` which results in `\n` in function body after `Array.prototype.join`:
`... Array.prototype.join; \nfunction print() {...`

That causes `SyntaxError: Invalid or unexpected token` when function is executed.

**Comment by filmic** [comment]
Other escaping related issue: #440

**Comment by filmic** [comment]
@boopathi Any hint when this will be fixed?
It is a blocker for anyone using Lodash `template` method i.e. in Backbone project.

**Comment by vigneshshanmugam** [comment]
@filmic Should be fixed once this PR https://github.com/babel/babili/pull/490 is merged
