### ISSUE TITLE
`babili --version` shows babel-cli version instead of babili version

### ISSUE THREAD

**Issue by goto-bus-stop** [babel/babili#418]
I was trying to check if my global `babili` installation was up to date, but:

```
> babili --version
6.22.2 (babel-core 6.22.1)
```

I expected it to show `0.0.11 (babel-core 6.22.1)` instead.

It seems like a pretty tough change with how the babili CLI wraps the babel CLI, unfortunately…

**Comment by boopathi** [comment]
Yeah. We should revisit CLI with options and other features.
