### ISSUE TITLE
A lethal combo.

### ISSUE THREAD

**Issue by WebReflection** [babel/babili#420]
Apologies for the fancy bug title but I couldn't think of any more descriptive one.

I've managed to isolate a series of issues in a single snippet that fails with babili `0.0.11`

```js
const that = (...args) => {
  let i = args.length;
  if (!i) return;
  else {
    const info = {args};
    while (false);
    return info;
  }
};
```

Despite being useless, it's valid JS syntax that's part of the real-world logic [I am using](https://github.com/WebReflection/notify-js/blob/modern/src/notify-js.js#L22-L38).

How to make above snippet **not** to fail?

Please note the following is a list of _OR_ conditions.
Each point itself will change the result, making babili happy.

  * use `do ; while(false);` instead
  * avoid the creation of the `info` constant and return directly `return {args};`
  * keep the `info` but `return {args};` instead
  * drop the else and use `if (i) {` instead
  * don't access `args.length` and `let i = 1;`
  * drop the `while(false)` line
  * use `if (false);` instead of `while (false);`

Thanks in advance for figuring out how come such little snippets can produce so many failures/not-failures scenarios.

**Comment by boopathi** [comment]
Nice example.

With #408, the output is 

```js
const that = (...a) => {
  let b = a.length;
  if (!b) return;

  return { args: a };
};
```

but still, it should be 

```js
const that = (...a) => {
  let b = a.length;
  if (b) return { args: a };
};
```

Ultimately, it could be

```js
const that = (...a) => a.length ? {args: a} : void 0;
```

But, because we treat `a.length` to possibly be a side-effecty getter and not computing side-effects between defn of b and usage of b (yet) (#221) , we are not able to safely replace it.

**Comment by WebReflection** [comment]
Please also keep in mind [in my case](https://github.com/WebReflection/notify-js/blob/modern/src/notify-js.js#L32-L36) I had to create a new variable in order to circumvent the failure.
