### ISSUE TITLE
Babili CLI

### ISSUE THREAD

**Issue by boopathi** [babel/babili#429]
Currently babili-cli is an alias to babel-cli with babili-preset and there is no way to specify babili options via CLI.

So, a new CLI that takes in babili-preset options () and some of babel options - for example - sourcemap support.

Examples:

```sh
babili --mangle=false # or babili --no-mangle
babili --mangle.topLevel 
babili --mangle.blacklist=Foo,Bar,Baz

babili --unsafe false
babili --unsafe.guards false # for option group
babili --unsafe.typeConstructors.string false # for delegating options to plugins in a group
```

All the options in [Preset Options](https://github.com/babel/babili/tree/master/packages/babel-preset-babili#options) should be available from the CLI.

File API: (examples)

```sh
babili --unsafe=false /path/to/input.js # outputs to STDOUT
babili --unsafe=false --out /path/to/out/dir /path/to/input/dir/*.js # takes multiple arguments

babili --unsafe=false --out /path/to/out --source-map /path/to/input.js # outputs sourcemap

# Option to provide input sourcemap - 
# Can be --input-source-map. But need some way to do for multiple files 
# Or can just NOT have support for soucemaps for multiple files via CLI
```

Related: 
+ #418 
+ Simplified JS API - #137

**Comment by nitin42** [comment]
Can you elaborate a little more? How the babel options and babili-preset  options would be read?

**Comment by boopathi** [comment]
The preset options are here - https://github.com/babel/babili/blob/master/packages/babel-preset-babili/README.md

**Comment by nitin42** [comment]
Ok. So the new cli could like this

With source maps support,
```
babili src -d lib --source-maps inline
```

With preset options, 
```
babili src -d lib --presets=babili
```
And there is no need to manually specify the individual plugins through the cli since preset is available but user may specify the different options. right ?

**Comment by nitin42** [comment]
Here is what I figured about the new cli:
* Standalone cli (not a wrapper around `babel-cli` #418 )
* Take presets options (`React` and `Flow`)
* Take options like `babel-cli` takes. (`sourcemap` support)
* Include babili options (the [link](https://github.com/babel/babili/tree/master/packages/babel-preset-babili) you gave me)  and other babel options (copy the files that will not compile, ignore some files)

**Comment by nitin42** [comment]
How would you picture the new cli ? Any example or something you can give me ? I am a little confused here!

**Comment by boopathi** [comment]
Updated the issue with examples.

**Comment by nitin42** [comment]
I was thinking if we could design the new cli like other minifiers. Like UglifyJS ?

**Comment by nitin42** [comment]
You could look at the options uglifyjs cli provides 😄

**Comment by vigneshshanmugam** [comment]
WIP #507
