### ISSUE TITLE
babilified code fails at runtime on browserified library

### ISSUE THREAD

**Issue by rosskevin** [babel/babili#431]
All details here: 
https://github.com/wnr/element-resize-detector/issues/71#issuecomment-280743474

```
❯❯❯ yarn list babel-core babel-preset-babili babili-webpack-plugin element-resize-detector react-sizeme                                                                                                   ⏎ feature/phantomjs ⬆ ✱
yarn list v0.20.3
├─ babel-core@6.23.1
├─ babel-preset-babili@0.0.11
├─ babili-webpack-plugin@0.0.10
├─ element-resize-detector@1.1.8
└─ react-sizeme@2.2.0
```

Offending browserified code:

```javascript
{"./utils":2}],2:[function(require,module,exports){
"use strict";

var utils = module.exports = {};

utils.getOption = getOption;                                   // Uncaught ReferenceError:?

function getOption(options, name, defaultValue) {
    var value = options[name];

    if((value === undefined || value === null) && defaultValue !== undefined) {
        return defaultValue;
    }

    return value;
}
```

Point of failure to run:

```javascript
        , function(V) {
            "use strict";
            var Y = V.exports = {};
            Y.getOption = G                 // Uncaught ReferenceError: G is not defined
        }
```

As I state in the other issue, this `./utils` appears to be injected by browserify, not by the project itself (I tried an experiment and renamed a potential conflicting method with the same results).

**Comment by rosskevin** [comment]
I just confirmed the same webpack build works with uglify.

**Comment by boopathi** [comment]
When I try that function, I get the output as 

```js
function foo(a, b) {
    "use strict";

    var e = b.exports = {};

    e.getOption = function (f, g, h) {
        var i = f[g];

        return (void 0 === i || null === i) && void 0 !== h ? h : i;
    };
}
```

Do you have a minimal repro case ?

**Comment by rosskevin** [comment]
I don't have a repro case, other than to say that I was using `babili-webpack-plugin` on an app and narrowed it down to the [`element-resize-detector` dist file](https://github.com/wnr/element-resize-detector/blob/master/dist/element-resize-detector.js).  The only thing curious about this file is that the library declares a [`getOption` in src](), and there are two in the dist file:
1. [browserified `getOption`](https://github.com/wnr/element-resize-detector/blob/master/dist/element-resize-detector.js#L148)
2. [library 'getOption'](https://github.com/wnr/element-resize-detector/blob/master/src/element-resize-detector.js#L313)

They use browserify so I assume that it is injecting this additional breaking (or possibly conflicting) method into the file.

This may not be a bug in babili, but actually a bug in the browserified dist file.  Do you see anything wrong with the dist file?  Any reason it won't load at runtime.

**Comment by boopathi** [comment]
I'm not able to reproduce this. It is possible that some of the fixes that went to master might have fixed it. Can you try it with latest master?
