### ISSUE TITLE
spread arguments in function signature disappeared after minification

### ISSUE THREAD

**Issue by f-roland** [babel/babili#432]
Hi There, 

I have a simple function that takes an arbitrary amount of arguments, and passes them to another function with the same signature, like this : 

```javascript
function foo(...args) {
    doSomething(...args);
}
```

When minified, I'm having an error because arguments in the function declaration have been dropped. Result is like
```javascript
function foo() {doSomething.apply(null, a)};
```
but a is undefined, and throws an error

I managed to fix the bug like this : 
```javascript
function foo(...args) {
   const _args = args;
   doSomething(..._args);
}
```

the minified function no longer has an empty signature, and it works.

**Comment by boopathi** [comment]
I'm getting the following output with `es2015` preset. - `{ presets: ["babili", "es2015"] }` 

```js
function foo() {
    doSomething.apply(void 0, arguments);
}
```

Looks like you're using an older version of babili which mangled `arguments`.
