### ISSUE TITLE
Increase of size between 0.0.9 and 0.0.11

### ISSUE THREAD

**Issue by FezVrasta** [babel/babili#434]
I just tried to upgrade my project from 0.0.9 to 0.0.11 and I noticed that now the minified bundle takes `17.29 kB` instead of the previous `16.56 kB`.

Is this expected due to some bug fixes you made or is it an actual bug?

This is the source code you can try to minify to reproduce the problem:
https://unpkg.com/popper.js@1.0.6/dist/popper.js

**Comment by boopathi** [comment]
Not sure. A couple of places required deopt to cover some corner cases. Maybe with some diff, it'll be easier to understand why the size increase happened.

**Comment by FezVrasta** [comment]
This is the old (0.0.9) minified file:
https://unpkg.com/popper.js@1.0.6/dist/popper.min.js

This is the new (0.0.11) minified file:
https://gist.githubusercontent.com/FezVrasta/3b07f8601bf381da2a200a27749d45a9/raw/0ca0fe4591a428b5fe0a94123bc52e27efab3ada/popper.min.js

**Comment by boopathi** [comment]
Closing this for now as the size has increased because of de-opts to get correctness over an unsafe transformation. Have placed a few TODO comments in simplify and DCE. Will revisit those later.
