### ISSUE TITLE
Big size of a vendor chunk in contrast with UglifyJsPlugin

### ISSUE THREAD

**Issue by budarin** [babel/babili#435]
When I build my simple project without babili plugin - I have 20k size of a vendor bundle (it contains only react.js)
After adding babili plugin - I have 40kb thought app file size is smaller more than in 3 times

How to decrease vendors chunk file size?

**Comment by boopathi** [comment]
Are you by any chance minifying twice ? 

This is a known issue - `babili(minified_code).length` > `minified_code.length`

**Comment by budarin** [comment]
What do you mean "minifying twice"?

**Comment by boopathi** [comment]
Running babili on already minified code. 

Do you have a sample project?

**Comment by budarin** [comment]
try it https://github.com/budarin/tmp-app

**Comment by boopathi** [comment]
It minifies as expected. Without babili plugin - 136kb, with babili plugin - 40kb. What's the issue ?

Closing this - I don't think this is a babili error.

**Comment by budarin** [comment]
without babili with UglifyJsPlugin - 20kb
with babili - 40kb

does this difference in sizes is normal?

**Comment by boopathi** [comment]
WIth `webpack.optimize.UglifyJsPlugin()` and removing class (as uglify doesn't understand class), I get 40kb vendor bundle, and not 20 kb. 

With Uglify:

```
                               Asset       Size  Chunks             Chunk Names
      vendor.cebc31b711d93d5766f2.js    41.1 kB    0, 2  [emitted]  vendor
      client.94ad7cac511e7a1d5b30.js  340 bytes    1, 2  [emitted]  client
                 chunk-manifest.json   75 bytes          [emitted]
    manifest.d41d8cd98f00b204e980.js    1.39 kB       2  [emitted]  manifest
```

WIth Babili:

```
                                   Asset       Size  Chunks             Chunk Names
          vendor.cebc31b711d93d5766f2.js    40.9 kB    0, 2  [emitted]  vendor
          client.94ad7cac511e7a1d5b30.js  394 bytes    1, 2  [emitted]  client
                     chunk-manifest.json   75 bytes          [emitted]
        manifest.d41d8cd98f00b204e980.js    1.45 kB       2  [emitted]  manifest
```

**Comment by budarin** [comment]
Thanks for explanation!

**Comment by budarin** [comment]
I'm sorry but on another device I get
```
Hash: 857893d432671fb205a6
    Time: 1791ms
                                   Asset       Size  Chunks             Chunk Names
          vendor.65aef0dc2817f59dccd2.js    20.1 kB    0, 2  [emitted]  vendor
          client.b1146cae4401b650e366.js  298 bytes    1, 2  [emitted]  client
                     chunk-manifest.json   75 bytes          [emitted]  
        manifest.d41d8cd98f00b204e980.js    1.44 kB       2  [emitted]  manifest
      vendor.65aef0dc2817f59dccd2.js.map  154 bytes    0, 2  [emitted]  vendor
      client.b1146cae4401b650e366.js.map  143 bytes    1, 2  [emitted]  client
    manifest.d41d8cd98f00b204e980.js.map  147 bytes       2  [emitted]  manifest
```

**Comment by boopathi** [comment]
Ah. Okay. So, `webpack -p` also adds one more thing - `process.env.NODE_ENV=production`. So all that dead code is removed. With babili, you have to use `webpack.DefinePlugin` and when using that I get 

With Babili: 
```
                                   Asset       Size  Chunks             Chunk Names
          vendor.65aef0dc2817f59dccd2.js    19.8 kB    0, 2  [emitted]  vendor
          client.94ad7cac511e7a1d5b30.js  394 bytes    1, 2  [emitted]  client
                     chunk-manifest.json   75 bytes          [emitted]
        manifest.d41d8cd98f00b204e980.js    1.45 kB       2  [emitted]  manifest
```

**Comment by budarin** [comment]
thanks a lot! 👍 )
please add this note to the documentation!
