### ISSUE TITLE
unnecessary escaping in string concatinaion

### ISSUE THREAD

**Issue by EladBezalel** [babel/babili#440]
Hey, 
For some reason I can't explain babili(?) escapes the backslash in the following string:
input:
```js
var x =  '\'cool\'' + 'test'
```
babili output:
```js
var x='\\\'cool\\\'test';
```
it only happens when i concat strings, it works perfectly when i input:
```js
var x =  '\'cool\'test'
```

I use the babili cli without any presets

p.s the [babel repl](https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=&targets=&browsers=&builtIns=false&code=var%20x%20%3D%20%20'%5C'cool%5C''%20%2B%20'test') doesn't show the problem (probably browser html escaping)

**Comment by Jamesernator** [comment]
I had the same issue, its not actually the backslash being quoted its the single quote, e.g. this is a simpler breaking case:

```js
// In code
const s = " ' " + "quote breaks"

// Out code
const s = " \\' quote breaks"
```

**Comment by goto-bus-stop** [comment]
Hmm I guess after #384 the strings are first run through jsesc by the minify-constant-folding transform, and then again by babel-generator. So backslashes end up being duplicated.

**Comment by boopathi** [comment]
What would be a correct way to handle these ?

/cc @mathiasbynens

**Comment by mathiasbynens** [comment]
As @goto-bus-stop said: don‘t escape strings twice.

The most sensible solution IMHO would be to make babel-generator pass `isScriptContext: true` to jsesc and to remove the additional/faulty escaping from minify-constant-folding.
