### ISSUE TITLE
babel-plugin-minify-constant-folding converts '' + '\'' to '\\\''

### ISSUE THREAD

**Issue by marcello3d** [babel/babili#450]
Getting this error in babili@0.0.11:

```js
var x = '' + '\''
```

becomes

```js
var x='\\\'';
```

should be

```js
var x='\''
```

If I disable this plugin with `{ evaluate: false }`, it works but obviously doesn't minify as much: 

```js
var x=''+'\''
```

I tried to pull down the repo and make actual tests, but I was getting hundreds of test failures by default so didn't want to debug that.

**Comment by boopathi** [comment]
#440
