### ISSUE TITLE
babilified code fails at runtime on SystemJS

### ISSUE THREAD

**Issue by gkovacs** [babel/babili#458]
I attach the original and minified code (it is a SystemJS bundle produced via jspm bundle, minified with babili 6.22.2). the original works correctly when loaded with SystemJS and executing

```javascript
SystemJS.import('icojs')
```

but the minified code throws an error at runtime (`Error: Te is not a constructor`). I have minified other SystemJS bundles without issue before, so this happens to be an exceptional case.

[original.txt](https://github.com/babel/babili/files/819386/original.txt)

[minified.txt](https://github.com/babel/babili/files/819387/minified.txt)

**Comment by vigneshshanmugam** [comment]
@gkovacs Can you provide a sample repo for this issue?

**Comment by gkovacs** [comment]
@vigneshshanmugam Sure, here: https://github.com/gkovacs/babili_bug_testcase

Clone that repo and start a webserver:

```
git clone https://github.com/gkovacs/babili_bug_testcase
cd babili_bug_testcase
npm install -g http-server
http-server
```

Then visit http://localhost:8080

Look at the console output. You will see it correctly imported icojs.

Now replace build.js with the version minified by babili (I have the output at build.min.js)

Now icojs will no longer import.

**Comment by vigneshshanmugam** [comment]
Having a look at it, figured out some bug in built-ins but not related to this issue.

**Comment by vigneshshanmugam** [comment]
The issue you are experiencing is already fixed in master, But i have found another issue which is mentioned already in #529 , Closing this in favor of that.
