### ISSUE TITLE
babel-generator: await (a||b) loses parentheses

### ISSUE THREAD

**Issue by marcello3d** [babel/babili#460]
```js
const a = async () => await (a||b)
```

becomes

```js
const a=async()=>await a||b;
```

should be

```js
const a=async()=>await(a||b);
```

**Comment by ljharb** [comment]
Why should it be? `await` has very low precedence; although I like the parens for readability, I don't think they're required for the code to do the right thing.

**Comment by marcello3d** [comment]
It behaves different in Chrome (56.0.2924.87, macOS 64-bit), as far as I can tell:

```js
const a = Promise.resolve(false)
const b = Promise.resolve('hi')
(async () => {
    console.log('await (a||b)', await (a||b))
    console.log('await a||b', await a||b)
})()
```
outputs:

```
await (a||b) false
await a||b Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: "hi"}
```

**Comment by ljharb** [comment]
Interesting - we should figure out what the spec says, just in case it's a chrome bug.

**Comment by marcello3d** [comment]
I'm not really sure how to read the [ecmascript spec](https://tc39.github.io/ecma262/)—it's pretty opaque to me. I can't even find the word "precedence," and "await" shows up almost everywhere.

One other data point: the babel regenerator seems to have the same behavior as Chrome.

I'll check out [Firefox Developer](https://hacks.mozilla.org/2016/12/asyncawait-arrive-in-firefox/) once I'm on a faster connection.

**Comment by marcello3d** [comment]
Does this section mean anything to you? https://tc39.github.io/ecmascript-asyncawait/#UnaryExpression

**Comment by marcello3d** [comment]
Firefox has the same result:
```
await (a||b) false 
await a||b Promise { <state>: "fulfilled", <value>: "hi" }
```

**Comment by ljharb** [comment]
K, looks like it's confirmed as a bug :-)

**Comment by goto-bus-stop** [comment]
Seems like a `babel-generator` bug, it happens even without any plugins:

```
➜  /tmp cat .babelrc
cat: .babelrc: No such file or directory

➜  /tmp cat test.js
const a = async () => await (a||b)

➜  /tmp babel test.js
const a = async () => await a || b;
```

**Comment by hzoo** [comment]
@babel-bot move to babel/babel

**Comment by hzoo** [comment]
Hey @marcello3d! I've [moved your issue](https://github.com/babel/babel/issues/5428) to the correct repository. Please make sure to keep an eye on the new issue for the latest information.

**Comment by hzoo** [comment]
^ this is so cool 😍

**Comment by hzoo** [comment]
Fixed https://github.com/babel/babel/issues/5428 via https://github.com/babel/babel/issues/5433
