### ISSUE TITLE
function param get optimized unexpectedly

### ISSUE THREAD

**Issue by steambap** [babel/babili#463]
I have babili version 0.0.12.

If I have a function with a parameter called window
```JavaScript
function doSomething(window) {
  if (!window) {
    return [];
  }
  
  // ...
}
```

babili think `!window` will always return false and that part of code will get optimized.

**Comment by hzoo** [comment]
Hey @steambap! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by vigneshshanmugam** [comment]
@steambap Not seeing this issue in the babili 

REPL - https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=chrome%20%3C%2040&builtIns=false&experimental=false&loose=false&spec=false&code=function%20doSomething(window)%20%7B%0A%20%20if%20(!window)%20%7B%0A%20%20%20%20return%20%5B%5D%3B%0A%20%20%7D%0A%7D&playground=true

Can you give more details?

**Comment by steambap** [comment]
Sorry, it looks like my problem come from babili-webpack-plugin
