### ISSUE TITLE
babel-plugin-transform-property-literals breaks 0 padded property names

### ISSUE THREAD

**Issue by GabbeV** [babel/babili#464]
I have an api that gives me an object like this:
```
data = {
  "00": { ... },
  "01": { ... },
  "02": { ... }
  `...`
}
```
When accessing data["00"] babili convets it to data[0] breaking the code.

**Comment by hzoo** [comment]
Hey @GabbeV! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by boopathi** [comment]
You can use 

```js
properties: {
  memberExpression: false,
  propertyLiterals: false,
}
```

as your [babili options](https://github.com/babel/babili/tree/master/packages/babel-preset-babili#option-groups)

or you can pass 

```js
properties: false
```

in your options.

**Comment by GabbeV** [comment]
Thank you @boopathi, that works great for a temporary fix. I tested and it seems like it's enough to just disable memberExpressions. I would still consider it a bug though as it should be avoidable by checking if the numeric strings are 0 padded.
