### ISSUE TITLE
Readme benchmarks

### ISSUE THREAD

**Issue by jacobmischka** [babel/babili#465]
I'm having a difficult time understanding what the benchmarks in the readme suggest, both because of their formatting (things don't seem to be lining up correctly) and because I'm not entirely sure what each column represents. Also, it's not clear what the conditions are for each test, like which browsers being targeted if they're all not just targeting ES5.

I assume that "win" means `<non-minified size> - <minified size>`, but I'm not completely convinced, because things don't seem to make sense if that were true (closure js being significantly better than regular closure for react, for example).

The first issue can be alleviated using tables instead of the current white space separated values, and that might be enough to end up fixing the second issue too.

Thanks!

**Comment by hzoo** [comment]
Hey @jacobmischka! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by jacobmischka** [comment]
Wow, I'm now convinced you're just actually a robot @hzoo, it actually explains a lot. :wink:

**Comment by kzc** [comment]
If anyone is updating the benchmarks table it would be nice to see the versions of the various minifiers listed.

**Comment by boopathi** [comment]
I sent a PR (which is linked above this message). Feel free to review it.

**Comment by jacobmischka** [comment]
I think that looks much better, thanks!
