### ISSUE TITLE
[Improvement] DCE should always propagate consts with number/string literals

### ISSUE THREAD

**Issue by AshleyScirra** [babel/babili#471]
babel-plugin-minify-dead-code-elimination can do the following transform:

```
function test(x)
{
  const foo = "bar";
  thing(foo);
}
```

to: `function test(){thing("bar");}`

Note the const declaration `foo` was removed and its value "bar" directly inserted to the call site.

However if you add a second reference:

```
function test(x)
{
  const foo = "bar";
  thing(foo);
  thing(foo);
}
```

this no longer optimises - the const declaration is kept:

`function test(){const foo="bar";thing(foo);thing(foo);}`

I wrote a [string deduplicator](https://github.com/AshleyScirra/babel-plugin-minify-string-literals) plugin that did the reverse: it would take `thing("bar");thing("bar");` and turn it in to `const foo="bar";thing(foo);thing(foo);`. However, this turned out to *increase* the gzip size, even though the uncompressed source is often shorter (assuming the string literals are long enough).

Therefore it follows that if DCE can do the reverse - and turn the second case in to:

`function test(){thing("bar");thing("bar");}`

then the gzip size ought to be reduced.

I don't think this needs to be smarter than handling number and string literals, it will still be effective in many cases and it avoids having to do any side-effects proof.

**Comment by hzoo** [comment]
Hey @AshleyScirra! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by AshleyScirra** [comment]
Looks like a semi-arbitrary limitation of 1 reference? https://github.com/babel/babili/blob/master/packages/babel-plugin-minify-dead-code-elimination/src/index.js#L258
Could be an easy fix then?

**Comment by boopathi** [comment]
Related: https://github.com/babel/babili/pull/221#issuecomment-260615569

**Comment by boopathi** [comment]
Will continue this in #498
