### ISSUE TITLE
Parent scope variable reference "optimized-out"

### ISSUE THREAD

**Issue by alippai** [babel/babili#473]
```js
function a() {
  var index = 0;
  for (var c = 0; c < 5; c++) {
    iterate();
  }

  function iterate() {
    return index;
  }
}
```
becomes:
```js
function a() {
    function b() {
        return d
    }
    for (var d = 0, e = 0; 5 > e; e++) b()
}
```
Note the wrong  `d` declaration scope in the output.

http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=latest&targets=&browsers=&builtIns=false&code=function%20a()%20%7B%0D%0A%20%20var%20index%20%3D%200%3B%0D%0A%20%20for%20(var%20c%20%3D%200%3B%20c%20%3C%205%3B%20c%2B%2B)%20%7B%0D%0A%20%20%20%20iterate()%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20function%20iterate()%20%7B%0D%0A%20%20%20%20return%20index%3B%0D%0A%20%20%7D%0D%0A%7D

**Comment by hzoo** [comment]
Hey @alippai! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by alippai** [comment]
Found some already filed issues, maybe related: https://github.com/babel/babili/issues/430 https://github.com/babel/babili/issues/412

**Comment by boopathi** [comment]
Those are `let` to `var` binding conversion issues. In your example, it seems to be correct code. `index` is converted to `d` and both are `var`s. So the scope is unaltered. In function `b`, `d` is still accessible.

**Comment by alippai** [comment]
Ummm, this was an oversimplified example and this way it seems to be the same issue as linked, right?
```
function parallelForEach(list, fn, para = 5) {
  var index = 0;
  const promises = [];
  for (let c = 0; c < para; c++) {
    promises.push(iterate());
  }

  function iterate() {
    if (index < list.length) {
      fn(list[index++]);
      iterate();
    }
  }
}
```
Feel free to close, if it's a duplicate.
