### ISSUE TITLE
Invalid destructuring assignment with Simplify Plugin

### ISSUE THREAD

**Issue by brettjurgens** [babel/babili#476]
here's a minimal reproduction:

[Babel REPL Link](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=true&presets=&targets=&browsers=chrome%2052&builtIns=false&experimental=true&loose=false&spec=false&code=const%20fn%20%3D%20(x)%20%3D%3E%20%7B%0A%20%20let%20arr%20%3D%20%5B1%2C2%5D%3B%0A%20%20let%20a%20%3D%20null%3B%0A%20%20let%20b%20%3D%20null%3B%0A%0A%20%20if%20(0%20%3C%20x.getIn(%5B'a'%5D))%20%7B%0A%20%20%20%20%5Ba%2C%20b%5D%20%3D%20arr%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20%5Ba%2C%20b%5D%20%3D%20arr%3B%0A%20%20%7D%0A%0A%20%20console.log(a%2Cb)%3B%0A%7D%3B%0A)

input:
```js
const fn = (x) => {
  let arr = [1,2];
  let a = null;
  let b = null;

  if (0 < x.getIn(['a'])) {
    [a, b] = arr;
  }
  else {
    [a, b] = arr;
  }

  console.log(a,b);
};
```

output:
```js
const fn = (c) => {
  let d = [1, 2],
      e = null,
      f = null;
  0 < c.getIn(['a']) ? [e, f] = d : [e, f] = d, console.log(e, f);
};
```

removing the `babel-plugin-minify-simplify` plugin fixes the issue. additionally, assigning `0 < x.getIn(['a'])` to a variable and using that in the `if` fixes it.

**Comment by hzoo** [comment]
Hey @brettjurgens! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by boopathi** [comment]
This is so weird ... 

```js
0 < foo.bar(['baz']) ? [a,b]=[] : [a,b]=[];
```

is a **SyntaxError**

while this - is NOT.

```js
0 < foo.bar([]) ? [a,b]=[] : [a,b]=[];
```

The diff,

```diff
- 0 < foo.bar([  ]) ? [a,b]=[] : [a,b]=[]; // Not a Syntax Error
+ 0 < foo.bar(['']) ? [a,b]=[] : [a,b]=[]; // Syntax Error
```

**Comment by boopathi** [comment]
I guess it is a Chrome bug.

That is not a SyntaxError on Firefox or Safari or Babel.

**Comment by brettjurgens** [comment]
i'll open a bug on the v8 tracker.

thanks!
