### ISSUE TITLE
2 extra line breaks are added

### ISSUE THREAD

**Issue by bfred-it** [babel/babili#484]
```sh
$ node --version
v7.2.0

$ babili --version
6.24.0 (babel-core 6.24.0)

$ touch test.js

# Empty input
$ cat test.js | wc -c
       0

# 2-bytes output
$ babili test.js | wc -c
       2
```

**Comment by hzoo** [comment]
Hey @bfred-it! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by vigneshshanmugam** [comment]
@bfred-it Interesting, its happening because of the options passed to childprocess spawn

```
{
stdio: "inherit"
}
```
