### ISSUE TITLE
Document programatical usage

### ISSUE THREAD

**Issue by medikoo** [babel/babili#491]
I wanted to use this minifier programmatically, still documentation is surprisingly silent on how to do that.

```javascript
var babili = require("babili");

// and then?
var minified = babili(sourceCode); // ?
```

**Comment by hzoo** [comment]
Hey @medikoo! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by vigneshshanmugam** [comment]
@medikoo https://github.com/babel/babili/tree/master/packages/babel-preset-babili#via-node-api

**Comment by medikoo** [comment]
@vigneshshanmugam thanks, still it's a pity I need to work through `babel-core` to somehow achieve that.

It'll be way nicer if it's provided naturally as input/output processor (same as UglifyJS), and not as a fixed plugin to some ecosystem not everyone uses.

**Comment by boopathi** [comment]
Duplicate #137
