### ISSUE TITLE
console.log.bind(console) still being removed

### ISSUE THREAD

**Issue by motss** [babel/babili#493]
## Description

[PR#421](https://github.com/babel/babili/pull/421) still does not solve the problem that `console.log.bind(console)` is still being removed after the build.

Consider the simple script below:

```js
// Using `debug`.
const Debug = require('debug');

const debug = Debug('test-debug');

debug.log = console.log.bind(console);
debug.error = console.error.bind(console);
```

  <details>
    <summary>.babelrc</summary><p>
    
*  
    ```json
    {
      "comments": false,
      "presets": [
        [ "env", { "targets": { "node": "current" } } ],
        "babili"
      ],
      "plugins": [
        "transform-remove-console"
      ]
    }
    ```
</p></details>

  <details>
    <summary>package.json</summary><p>
    
*  
    ```json
    "devDependencies": {
      "babel-cli": "^6.14.0",
      "babel-plugin-transform-remove-console": "^6.8.0",
      "babel-polyfill": "^6.16.0",
      "babel-preset-babili": "0.0.12",
      "babel-preset-env": "^1.1.8",
    }
    ```
</p></details>

## Expected output after `babili`:

```js
'use strict';
const Debug=require('debug'),debug=Debug('test-debug');
debug.log=console.log.bind(console),debug.error=console.error.bind(console);
```

## Actual output after `babili`:

```js
'use strict';
const Debug=require('debug'),debug=Debug('test-debug');
debug.log=function(){},debug.error=function(){};
```

**Comment by hzoo** [comment]
Hey @motss! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by boopathi** [comment]
You're using `transform-remove-console` in your plugins which is supposed to remove console.* statements or nullify the effect of console.* statements and is working as expected.

You can avoid using `transform-remove-console` plugin in your babelrc and babili should not remove the console.* statements by default.
