### ISSUE TITLE
babel-plugin-minify-builtins not minified?

### ISSUE THREAD

**Issue by FezVrasta** [babel/babili#500]
I have this options object I use with the Babel JS API:

```
const options = {
  presets: ['babili', !!argv.es5 && ['es2015', { modules: false }], 'stage-2'],
  plugins: ['minify-builtins'],
  comments: false,
  minified: true,
  compact: true,
  sourceMaps: true,
  inputSourceMap,
};
```

I notice that `_Mathfloor` & co aren't minified to a single letter variable, I wonder if this is a bug?

**Comment by hzoo** [comment]
Hey @FezVrasta! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by goto-bus-stop** [comment]
This should be fixed on master. See also #425
