### ISSUE TITLE
Why we need es2015 preset in .babelrc?

### ISSUE THREAD

**Issue by rudyhuynh** [babel/babili#502]
Hi, I'm new to Babel. I'm following the instruction using babili as babel preset like this:
```
{
  "presets": ["es2015"],
  "env": {
    "production": {
      "presets": ["babili"]
    }
  }
}
```
My code just transformed into minified es5, not minified es6.
Why we need `"presets": ["es2015"],` in here?

**Comment by hzoo** [comment]
Hey @rudyhuynh! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by vigneshshanmugam** [comment]
@rudyhuynh Please remove the `es2015` preset from your config if do not want to apply transformations. `es2015` preset compiles ES2015 to ES5. 

The config there denotes in the normal scenario run `es2015` preset and if the env is set to production then run babili preset.
