### ISSUE TITLE
Array Deconstruct with no space

### ISSUE THREAD

**Issue by taozhi8833998** [babel/babili#511]
I have an problem with `babili` when using array deconstruct feature

```js
const [one, two, three, four] = [1,2,3,4]
const file_date = `${one}${two}${three}${four}`
console.log(file_date)
```

when using 
`babel test.js -o compress_test.js --presets=babili`
I got the following code

```js
"use strict";const[f, a, b, c]=[1,2,3,4],file_date=`${f}${a}${b}${c}`;console.log(file_date);
```

While pay attention to the *no space* between `const` and variable `[f, a, b, c]`, and of course I got error.

- node version lts/arbon
- babel version 6.24.1 (babel-core 6.24.1)

**Comment by hzoo** [comment]
Hey @taozhi8833998! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by taozhi8833998** [comment]
sorry for just post an title without contents,  occupied by sth and add the contents now.

**Comment by vigneshshanmugam** [comment]
Node argon(v4.2.0) doesn't support array destructuring. 

REPL output - https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=&targets=&browsers=chrome%2052&builtIns=false&debug=false&experimental=true&loose=false&spec=false&code=const%20%5Bone%2C%20two%2C%20three%2C%20four%5D%20%3D%20%5B1%2C2%2C3%2C4%5D%0Aconst%20file_date%20%3D%20%60%24%7Bone%7D%24%7Btwo%7D%24%7Bthree%7D%24%7Bfour%7D%60%0Aconsole.log(file_date)&playground=false
