### ISSUE TITLE
transform-property-literals should not transform numbers outside safe range

### ISSUE THREAD

**Issue by SEAPUNK** [babel/babili#515]
```js
{
  '306887048457879552': {}
}
```

becomes

```js
{
  306887048457879550: {}
}
```

note the 0 at the end

**Comment by postspectacular** [comment]
this already seems to be fixed, just not released?

https://github.com/babel/babili/commit/c545d0a6b858e64aca5b46af85847985352ba6e2#diff-085799e127967f84d83f6427b98b8a58R16

**Comment by SEAPUNK** [comment]
Seems so. Thanks.
