### ISSUE TITLE
Incorrect destructuring assignment when minifying to ES6

### ISSUE THREAD

**Issue by ykagan** [babel/babili#524]
When using destructuring assignment on arrays with mangle-names enabled.
```
const me = () => {
 let [a,b,c,d] = [1,2,3,4];
 [a,b,c,d] = [5,6,7,8];
 console.log(a,b,c,d);
}
```
The second assignment produces this incorrect code:
```
const me=()=>{let[e,f,g,h]=[1,2,3,4];[e,h,g,h]=[5,6,7,8],console.log(e,f,g,h)};
```
Note that transforming to ES5 or turning off mangle names produces correct code.

**Comment by boopathi** [comment]
Thanks. #390 fixed this and this doesn't happen in current master. I'll release a new version after a few more fixes get in.
