### ISSUE TITLE
Problems with 'var _this = this'

### ISSUE THREAD

**Issue by Julisep** [babel/babili#530]
I have a very minor problem and just need to know which options I have to pass to solve it.

When my `.js` file is minified the keyword `this` is replaced with `_this`. In most modules this is no problem, but in my case `this` referees not to the global scoped `this`, but to the local scope. 
Therefor I have to prevent babili from proceeding with this behavior.

My current settings are 
```
{
    mangle: {
        keepClassName: true,
        topLevel: false,
    },
    simplify: true,
    simplifyComparisons: false,
}
```

So I´d like to gain knowledge about how to prevent babili form replacing `this` like this. ;)

**Comment by vigneshshanmugam** [comment]
@Julisep Can you give a sample code/repo to reproduce the issue?

**Comment by Julisep** [comment]
Well I guess I found the the problem to be located inside babel itself and being desired behavior.

So I am in no need for further help.

Thanks for your support
