### ISSUE TITLE
Example 'keepClassNames' in gulp-babili README is wrong

### ISSUE THREAD

**Issue by arantes555** [babel/babili#532]
Hello,

I know it's not a big issue, but I just spent 30 minutes figuring out why my code didn't work, and it was because I had copied the example from gulp-babili's README.

Long story short, in the file https://github.com/babel/babili/blob/master/packages/gulp-babili/README.md , the example given uses the option `keepClassNames` when in fact the option is `keepClassName`.

**Comment by boopathi** [comment]
Thanks. PR welcome 😃 .
