### ISSUE TITLE
Error message missing

### ISSUE THREAD

**Issue by user732965** [babel/babili#535]
Please provide an (maybe optional) error message to hint errors as references to / calls of (static) class functions that are not present or misspelled.

**Comment by hzoo** [comment]
A good suggestion, but this is more of a linting rule (possibly out of scope for Babel)? I would write a custom eslint plugin or maybe via something like webpack since you'd need to know about multiple files and their exports. Babel focuses on a per file transform atm, and this issue would be more for babel/babel rather than for the minifier.

**Comment by user732965** [comment]
Dear Henry

Thanks for for your answer.

About the topic:
Yesterday was my first time contact with node/npm/babel/babili, which i found by searching for a JavaScript minimizer capable of "class" definitions. At that time i couldn't determine which of the many involved components causes the minimized output to abort. Although i accept your argument, in the end what makes a project success or not is how easy or hard it is to get it running. So i rather like multiple redundant error messages than none. Still i think it would be a plus to babili to at least emit a little hint. If the terminal just stays empty there are so many possible reasons for that, even aside babili, that it can be a hard time searching.

The hardest problem over all was to recognize how the usual workflow is: act by project from within the project source dir, install modules projectwise vs. global. Yes, that is again not a direct babili problem and i guess anywhere in the deeps of docs that is explained, but - it is not obviously hinted!

The short usage chapter worked fine and fast, but i also wanted that "remove-console" functionality, so i had to dig very deep yesterday. The time i spent could have been a shift less if there would be a paragraph, page or document describing a use case how to install, config and run babili with extended features offered in the babel/node-"world", to make it professionell usable. All you project staff surely did these experiences once and it would be a great, great help to share that too, especially if someone, as me, is just looking for a minimizer and is first time confronted to install and learn the complete sw-family.

Compare it with a coffe shop: It's ok if you go to the counter, pay an get your coffee. But if you can sit down and get your coffee served the experience is much, much better (and the tips will be so too).

So, have a good time and thank's for babili.

Yours sincerely
