### ISSUE TITLE
Minify options

### ISSUE THREAD

**Issue by boopathi** [babel/babili#54]
Since it is a preset, there won't be any options passed to the minifier. 

for example,
- mangle topLevel names
- mangle eval accessible bindings - don't deopt because of the presense of eval
- apply unsafe optimizations like - `!==` to `!=`, `>=` to `<`
- drop debugger & console statements or just one of them
- preserve fn args and fn name for code depending on fn.length & fn.name

etc...

How to support these as options to be passed to the minifier - when used as a CLI or a Preset?

**Comment by jacott** [comment]
I would much appreciate a `keepClassNames` option
