### ISSUE TITLE
Is this normal that code is not mangled at all?

### ISSUE THREAD

**Issue by evaldsurtans** [babel/babili#552]
Is this normal that code is not mangled at all?

Online:
http://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=react%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=%2F%2F%20Example%20ES2015%20Code%0Aclass%20Mangler%20%7B%0A%20%20constructor(program)%20%7B%0A%20%20%20%20this.program%20%3D%20program%3B%0A%20%20%7D%0A%7D%0Anew%20Mangler()%3B%20%2F%2F%20without%20this%20it%20would%20just%20output%20nothing%20since%20Mangler%20isn't%20used

Screenshot:
http://www.evernote.com/l/ACkz7GkgNUNAH6B8rNI3nB3nBIQj2UybhfA/

Unlike example here:
http://www.evernote.com/l/ACmE1tdctw1NxIne-SjF-iovf4avRmCAdw0/

**Comment by goto-bus-stop** [comment]
Identifiers in the "top-level" scope are not mangled by default. When using the babili preset, you can specify the `mangle.topLevel` option to change that behaviour.

```js
➜ ls -A
.babelrc  test.js

➜ cat test.js 
// Example ES2015 Code
class Mangler {
  constructor(program) {
    this.program = program;
  }
}
new Mangler(); // without this it would just output nothing since Mangler isn't used%                                                                                   

➜ cat .babelrc
{
  "presets": [
    ["babili"]
  ]
}

➜ babel test.js
class Mangler{constructor(a){this.program=a}}new Mangler;
```

And now with the `mangle.topLevel` option:

```js
➜ cat .babelrc 
{
  "presets": [
    ["babili", {
      "mangle": { "topLevel": true }
    }]
  ]
}

➜ babel test.js
class a{constructor(a){this.program=a}}new a
```

**Comment by evaldsurtans** [comment]
Thank you!
