### ISSUE TITLE
Exported class is made anonymous

### ISSUE THREAD

**Issue by brianmhunt** [babel/babili#555]
Babili is making classes anonymous, and it's not clear how to turn this feature off.

e.g. Given

```javascript
class X extends Y {}
module.exports = X
```

the result after babilification is .

```javascript
module.exports = class extends Y {}
```

This is probably fine in most cases, but sometimes one may need `X.name`, which will not be `X` when it's an anonymous class.

Obviously one can design around this, but for large legacy systems it's a problem.

It wasn't clear after some time of reviewing and tinkering with the plugins which is causing this, or how to disable it.

Cheers :beers:

**Comment by boopathi** [comment]
There is `keepClassName` in mangler options. And also there is `blacklist`. 

https://github.com/babel/babili/tree/master/packages/babel-plugin-minify-mangle-names#options

**Comment by brianmhunt** [comment]
Oh I see, thanks.  I had set `mangle: false` and assumed the plugin would stop doing things, so I didn't delve deeper.  The keepClassName is perfectly named.

It was not apparent that option existed or how it interacted, from the main preset options documentation. Being pointed to the docs satisfies the issue for me, but I will leave it open in case someone feels a need to document (but please close if otherwise).

Cheers

**Comment by boopathi** [comment]
There is documentation, I'll close this. If it can be made clearer, I'd appreciate a PR. Thanks.
