### ISSUE TITLE
Variable hoisting should split declaration from initialisation

### ISSUE THREAD

**Issue by ashsearle** [babel/babili#558]
Variables declared inside blocks aren't being hoisted the way a JavaScript interpreter does it.

Inside a function `if (something) { var foo = 'bar'; }` should be treated as `var foo; if (something) { foo = 'bar';` - this isn't happening, causing behavioural change in minified code.

In a browser, this logs `pass`:
```js
(function() {
  if (false) {
    var foo = true;
  }

  if (foo === true) {
    console.log('fail');
  } else {
    console.log('pass');
  }
})()
```

In babili repl, [the output is `fail`](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=stage-3&targets=&browsers=&builtIns=false&debug=false&code=(function()%20%7B%0A%20%20if%20(false)%20%7B%0A%20%20%20%20var%20foo%20%3D%20true%3B%0A%20%20%7D%0A%20%20if%20(foo%20%3D%3D%3D%20true)%20%7B%0A%20%20%20%20console.log('fail')%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20console.log('pass')%3B%0A%20%20%7D%0A%7D)()&experimental=true&loose=false&spec=false&playground=true):

The code should be treated as:
```js
(function() {
  var foo;
  if (false) {
    foo = true;
  }

  if (foo === true) {
    console.log('fail');
  } else {
    console.log('pass');
  }
})()
```

**Comment by boopathi** [comment]
Thanks. I'll look into this.

**Comment by vigneshshanmugam** [comment]
Did the check on latest babili master and the issue seems fixed. 
```js
(function () {
  var a;
  !0 == a ? console.log('fail') : console.log('pass');
})();
// logs pass
```

**Comment by ashsearle** [comment]
@vigneshshanmugam What's the right way to check things with master?  I tried by adding a test to `packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js`, and got the failure - but understand that's testing one module in isolation.

(I had assumed that babeljs.io would be running the latest version of babili, but have just checked `window.Babili.version` in a console and see it's still using 0.0.9 which is 6 months old, so... I guess that needs updating!)

**Comment by vigneshshanmugam** [comment]
you can clone babili and run `yarn link` or `npm link` on the corresponding repo. 

Yeah REPL runs older version of babili, we will update that soonish.
