### ISSUE TITLE
SyntaxError: Unexpected token const

### ISSUE THREAD

**Issue by deniss-muhla** [babel/babili#560]
We have unfinished generator function with unused variables: 
```js
function* updateTemplate() {
    try {
        while(true) {
            const {
                type,
                userId
            } = yield take(actions.UPDATE_TEMPLATE);

            const {
                response,
                error
            } = yield call(postTemplate, 'update', userId);
        }
    } catch(e) {
        if (e.name !== 'SagaCancellationException') {
            console.log(e);
        }
    }
}
```
Which was transformed into this with babili options { mangle: false }:

function*updateTemplate(){try{for(;;)const{type,userId}=yield(0,_effects.take)(actions.UPDATE_TEMPLATE),{response,error}=yield(0,_effects.call)(postTemplate,'update',userId)}catch(e){'SagaCancellationException'!==e.name&&console.log(e)}}

For loop scope curly brackets was removed and we getting node.js error:
SyntaxError: Unexpected token const

**Comment by deniss-muhla** [comment]
Added { mergeVars: false } to babili option as temporary solution.

**Comment by vigneshshanmugam** [comment]
bug in simplify plugin
