### ISSUE TITLE
Class names not mangled

### ISSUE THREAD

**Issue by gauntface** [babel/babili#562]
I'm using Babili with Rollup and at the moment babili is removing comments and its mangling variable names, but class names are remaining untouched, not sure why. Everything I can see / have tried, this should either work out the box.

```javascript
const babel = require('rollup-plugin-babel');

// This is passed into rollup plugins
const babelPlugin = babel({
  presets: [['babili', {
    comments: false,
  }]],
});
```

The resulting code is in an iife, so I don't think there is any issue with global scope and renaming. Does anyone have any ideas / tips?

**Comment by goto-bus-stop** [comment]
Do you have some example code or perhaps a small project to reproduce?

Note that `rollup-plugin-babel` runs before the code is bundled, so even if rollup adds an iife around the output, it won't yet be there when babili runs.

**Comment by gauntface** [comment]
I don't have a small example, but this is a result of workbox: https://github.com/GoogleChrome/workbox/

It's likely that Rollup  is our issue by the sound of it. Would it be insane to use Rollup for bundling and module format and then use babel to minify in a seperate step?

**Comment by goto-bus-stop** [comment]
> Would it be insane to use Rollup for bundling and module format and then use babel to minify in a seperate step?

Not at all!

**Comment by boopathi** [comment]
Short answer: 

+ There is [rollup-plugin-babili](https://www.npmjs.com/package/rollup-plugin-babili).
+ This is the same issue as using babili with `babel-loader` vs `babili-webpack-plugin` when webpack is the bundler.

Long answer:

+ Rollup plugins have two handlers - `transform` and `transformBundle` [(Ref)](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins)
+ rollup-plugin-babel uses `transform` [(source)](https://github.com/rollup/rollup-plugin-babel/blob/e4720c1249d63b38ea899e9cd74b3944b9d7953f/src/index.js#L60) - So Babel first. The babili preset will receive all the code in a file as toplevel and minify the file.
+ rollup-plugin-babili uses `transformBundle` [(source)](https://github.com/Comandeer/rollup-plugin-babili/blob/master/src/index.js#L29). So Rollup first and babili happens next on the entire bundle.
+ For the webpack context (loaders vs plugins), a little more information is [here in babili-webpack-plugin docs](https://github.com/webpack-contrib/babili-webpack-plugin#why).

**Comment by gauntface** [comment]
Thanks for the extra info @boopathi. I did try running with an option that looked like it would mangle top level classes and functions, but that didn't seem to take affect but by the sounds of it, if it works, it would be preferable in rollup-plugin-babel (i.e. using transform)

**Comment by boopathi** [comment]
Are you facing any issues with 

```js
{
  presets: [
    [
      "babili",
      {
        mangle: { topLevel: true }
      }
    ]
  ]
}
```
