### ISSUE TITLE
[babili 0.2.1] Conflict when running es2015 + babili presets

### ISSUE THREAD

**Issue by diervo** [babel/babili#563]
After upgrading to 0.2.1, when running preset es2015 and babili together, some of the plugins throw, most likely due to some inter dependency and plugin execution order.

I don't have a small enough reproducible case yet (I'm compiling a really big file when it throws).
My hope is that you guys might have an idea of what could happen based on the changes between the previous version?

Otherwise I will either wait for @hzoo to finish the plugin dependency work, or will try to bring a more concrete use case to try to fix this issue.

**Comment by boopathi** [comment]
Is this the same error as #556 ?

Also, there are some known issues when used alongside es2015 preset - https://github.com/babel/babili/issues?q=is%3Aissue+is%3Aopen+label%3A%22with+es2015%22

**Comment by boopathi** [comment]
Closing this for now.

Please comment with more info (stack trace / minimal repro / any other clue to help drill down to the issue) and let's reopen the issue.
