### ISSUE TITLE
Nothing happens when used as preset

### ISSUE THREAD

**Issue by electerious** [babel/babili#564]
The babili preset isn't doing anything. The output looks exactly the same without it. No error or warning.

I've installed and added babili to my presets. The following options are passed to babel through babelify:

```json
{
  "plugins": [
     "transform-es2015-modules-commonjs"
  ],
  "presets": [
    "react",
    "babili"
  ]
}
```

Versions in use:

babel-plugin-transform-es2015-modules-commonjs v6.24.1
babel-preset-babili v0.1.2
babel-preset-react v6.24.1
babel v6.24.1
babelify v7.3.0

What I tried so far:

- Removing the react preset throws an error => The options are active.
- I've removed and reinstalled my dependencies to ensure that they are fresh/"up-to-date".
- Minification works fine when running the babili CLI directly.

**Comment by vigneshshanmugam** [comment]
Can you give link to a minimal repo to reproduce this issue?

**Comment by boopathi** [comment]
I see that you're using babelify - so browserify.

Babelify is applied to every file individually. There is a difference between applying it to one file and an entire bundle. More details is available here - https://github.com/babel/babili/issues/562#issuecomment-305963471 

I don't know if there is a browserify transform plugin that applies babel/babili on the entire bundle. Might be a good community contributed open source project for browserify with babili.

**Comment by electerious** [comment]
I was about to create a repo to reproduce this issue, but everything works fine now. Not sure what has changed. Thanks anyway!
