### ISSUE TITLE
Incorrect folding of Array.concat (babel-plugin-minify-constant-folding)

### ISSUE THREAD

**Issue by aphix** [babel/babili#577]
I've noticed a strange behavior due to the minify-constant-folding transform used in babili >= 0.1.0.

Test case:

```js
var a = ['first'];
var b = ['second'].concat(a);
// babel-preset-babili >= 0.1.0 produces:
// var b=['second',a];			(INCORRECT)

// babel-preset-babili <= 0.0.12 leaves untouched:
// var b=['second'].concat(a);		(CORRECT)

if (b[0] !== 'second' || b[1] !== 'first') {
	throw new Error('fail!')
} else {
	console.log('pass!');
}
```

Here's an alternate case, based on the example found in the package's [README](https://github.com/babel/babili/blob/master/packages/babel-plugin-minify-constant-folding/README.md):
```js
// README Example:
[a, b, c].concat([d, e], f, g, [h]);
// becomes [a, b, c, d, e, f, g, h]; 		(CORRECT)

// Functionally equivalent:
var x = [d, e];
[a, b, c].concat(x, f, g, [h]);
// becomes [a, b, c, x, f, g, h]; 		(INCORRECT)
```

For reference, here's my .babelrc I used to test/produce the above results:
```js
{
    "presets": [],
    "minified": true,
    "compact": true,
    "sourceMaps": true,
    "retainLines": true,
    "plugins": [
        "minify-constant-folding",
    ],
}
```
Let me know if you'd like any further information.

Thanks,
Aphix

**Comment by boopathi** [comment]
Thanks for the report. 

/cc @j-f1

**Comment by j-f1** [comment]
@boopathi Is there a way to protect against that? It doesn’t look like there is.

**Comment by swernerx** [comment]
This breaks https://github.com/sebastian-software/prepublish right now.

**Comment by j-f1** [comment]
@swernerx Sorry about the breakage. I didn’t realize that it could break that way. It should be fixed pending the next release. For now, you can just pin it to the last working version.
