### ISSUE TITLE
babel-plugin-minify-constant-folding v0.1.2

### ISSUE THREAD

**Issue by webyonet** [babel/babili#584]
The whole project started to fail when I update to version 0.1.2. I get a lot of errors and especially constructor error.

.babelrc

{
  "cacheDirectory": true,
  "plugins": [
    ["transform-runtime", {
      "helpers": true,
      "polyfill": false,
      "regenerator": true
    }],
    "jsx-control-statements",
    "transform-flow-strip-types",
    "transform-remove-console",
    "transform-remove-debugger",
    "minify-constant-folding",
    "minify-guarded-expressions",
    "minify-type-constructors",
    "transform-minify-booleans",
    "transform-property-literals",
    "minify-empty-function",
    ["minify-dead-code-elimination", { "optimizeRawSize": true }]
  ],
  "presets": [
    "es2017",
    "es2016",
    "es2015",
    "stage-0",
    "react"
  ]
}

**Comment by boopathi** [comment]
Can you elaborate more on what errors you get - 

1. Code to reproduce
1. Stack Trace

**Comment by webyonet** [comment]
parameters cannot be sent to the react components after this version 
and
other node_modules started to work inconsistently

**Comment by vigneshshanmugam** [comment]
@webyonet can you try with the new version 0.1.3, might have been the cause https://github.com/babel/babili/issues/576

**Comment by webyonet** [comment]
Thanks @vigneshshanmugam
