### ISSUE TITLE
Minify functions taking one string parameter

### ISSUE THREAD

**Issue by j-f1** [babel/babili#588]
`foo('bar')` can be shortened to ``foo`bar` ``, saving 2 bytes per call.

**Comment by j-f1** [comment]
In addition, minifying concatenations to template literals can save more bytes:

```js
foo('bar'+baz+'quux')
foo`bar${baz}quux`
```

**Comment by dashed** [comment]
I don't think this works since the first input to `foo` would be an array of strings?

**Comment by j-f1** [comment]
Correct! Thanks for pointing that out!

**Comment by boopathi** [comment]
I tried this already and it won't work - https://github.com/babel/babili/pull/387
