### ISSUE TITLE
Transpiled spread in array becomes incorrectly minified.

### ISSUE THREAD

**Issue by frzi** [babel/babili#589]
Hello,

Recently I've been having troubles minifying spreads in arrays, after being transpiled using Babel (using babel-preset-env).

The following code
```js
let a = [...document.body.children]
console.log(a)
```
becomes, after transpiling and minifying, the following:
```js
var a=[babelHelpers.toConsumableArray(document.body.children)];console.log(a);
```
Notice how the `babelHelpers.toConsumableArray` is called inside another array. The result is an array within an array.

To reproduce, the package.json:
```json
{
  "name": "babili-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "babel index.js -o index.min.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.25.0",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-babili": "^0.1.3",
    "babel-preset-env": "^1.5.2"
  }
}
```
And the .babelrc:
```json
{
	"presets": [
		["env", {
			"targets": {
				"ie": "11",
				"ios": "7",
				"android": "4.4"
			},
			"modules": false,
			"useBuiltIns": true
		}],
		"babili"
	],
	"plugins": [
		"external-helpers"
	]
}
```
I'd like to point out that, when you remove "babili" from the .babelrc, the code is transpiled correctly.

If I'm overlooking something incredibly obvious, please let me know. 😄

**Comment by j-f1** [comment]
You’ve got the same issue as #580. The issue has been fixed on `master`, and the maintainers said they’d do a release today.

**Comment by frzi** [comment]
Well, there you go. Thanks for the heads up!
