### ISSUE TITLE
Runtime error after compiling React

### ISSUE THREAD

**Issue by hph** [babel/babili#592]
I ran into an issue yesterday where I got runtime errors logged to the console in React event handlers. This only happens when the code is compiled in production mode (using Babili). I managed to work around the issue by simply not compiling the React files and using the provided minified files.

I've created a tiny repository with a minimal example with everything needed to reproduce the issue plus a workaround [here](https://github.com/hph/babili-bug-reproduction). This is what you'll get if you build the app:

<img width="397" alt="screen shot 2017-06-20 at 20 05 06" src="https://user-images.githubusercontent.com/1166565/27350970-ced5782e-55f3-11e7-89e3-bd8891725ec0.png">

Now, I'm not entirely sure whether this is really a bug in Babili or whether it might be something else, but it appears to be the case.

**Comment by vigneshshanmugam** [comment]
There was an issue with webpack 3 #590 which should be fixed with the latest release https://github.com/babel/babili/releases/tag/babili%400.1.4

**Comment by hph** [comment]
@vigneshshanmugam I'm happy to report that by updating to 0.1.4 everything works! Thank you for the help!

**Comment by vigneshshanmugam** [comment]
@hph Cool. thanks for the info 👍
