### ISSUE TITLE
minify-constant-folding concat evaluation bug

### ISSUE THREAD

**Issue by pshev** [babel/babili#595]
I have the following code:

```
const arr = () => [1, 2]
console.log([].concat(arr()))
```

When I minify it with webpack using `babili-webpack-plugin`, minify-constant-folding (version 0.1.2) changes:

```
[].concat(arr())
```
into:
```
[arr()]
```
which are clearly not the same.

**Comment by vigneshshanmugam** [comment]
Its already fixed in 0.1.3 version. https://github.com/babel/babili/blob/master/CHANGELOG.md#babili014-2017-06-20
