### ISSUE TITLE
Babili does not work with babel 7 due to clearCache deprecation

### ISSUE THREAD

**Issue by diervo** [babel/babili#600]
Due to https://github.com/babel/babel/pull/5494 `traverse.clearCache()` has been deprecated towards `traverse.cache.clear()`.

**Comment by diervo** [comment]
@boopathi  Not sure what is the state of work in progress towards upgrading to 7, but if you guys want I can do a PR with this change.

**Comment by vigneshshanmugam** [comment]
@diervo we have a PR already https://github.com/babel/babili/pull/487. Thanks :)
