### ISSUE TITLE
Spread array becomes a single argument after minifying

### ISSUE THREAD

**Issue by kysely** [babel/babili#603]
**Happens when used with`es2015`**

```javascript
// Example

const something = (one = 'Why? ', two = 'Be', three = 'cause') => {
    console.log(one+two+three)
}

const everybody = ['Every', 'body']

something('Who? ', ...everybody)

/*

Expected:
Who? Everybody

Actual:
Who? Every,bodycause

*/
```

**Comment by j-f1** [comment]
Are you on the latest version of Babili? This issue was fixed in the latest version.

**Comment by kysely** [comment]
Ooooh my gosh... you're right, I was on `0.1.3`, didn't realize it could be that since I started using Babili only few days ago.

Sorry for wrong issue!
