### ISSUE TITLE
Another "Cannot read property 'end' of null" error

### ISSUE THREAD

**Issue by zamb3zi** [babel/babili#615]
### Input ###

```js
function foo(arg) {
    const { y } = arg, { z, x = null } = y;
    return z ? z : null;
}
```

### Output ###
```
TypeError: test3.js: Cannot read property 'end' of null
    at _evaluate (C:\Users\John\Documents\GitHub\babili\packages\babili\node_modules\babel-traverse\lib\path\evaluation.js:159:57)
    at evaluate (C:\Users\John\Documents\GitHub\babili\packages\babili\node_modules\babel-traverse\lib\path\evaluation.js:65:17)
    ...
```
[REPL](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2016&targets=&browsers=&builtIns=false&debug=false&code_lz=GYVwdgxgLglg9mABMOcAUBDATgcwJSIDeAsAFCIWIQIDOURiAnogL6IC8i2OANAwF58AHh0RgQAGwmtRjANxlKiLAFMoILEn6IA_Im0AuMZIkLSLIA)

The following version does not produce an exception but generates incorrect output:
### Input ###

```js
function foo(arg) {
    const { y } = arg, { z, x = null } = y;
    return z;
}
```

### Output ###
```js
function foo(a){const{y:b}=a;return z}
```
[REPL](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2016&targets=&browsers=&builtIns=false&debug=false&code_lz=GYVwdgxgLglg9mABMOcAUBDATgcwJSIDeAsAFCIWIQIDOURiAnogL6IC8i2OANAwF58AHh0RgQAGwmtRjANxlKiLAFMoILEn4LSLIA)

Note: removing `, x = null` produces correct output. Alternatively returning `x + z` produces correct output ([REPL](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2016&targets=&browsers=&builtIns=false&debug=false&code_lz=GYVwdgxgLglg9mABMOcAUBDATgcwJSIDeAsAFCIWIQIDOURiAnogL6IC8i2OANAwF58AHh0RgQAGwmtRjANxlKiLAFMoILEn6IA1IiELSLIA))

**Comment by boopathi** [comment]
#622 fixes this
