### ISSUE TITLE
bracket  deleted but no semicolon added

### ISSUE THREAD

**Issue by Wang-NQXB** [babel/babili#634]
when i use babili to minify my code, i found it will cause bug when i don't write semicolon

#### Input Code

```js
if (condition) {
  foo()
} else {
  bar()
}
```

#### Actual Output
```js
if (condition) foo() else bar()
```

#### Expected Output
```js
if(condition)foo(); else bar()

if(condition){foo()}else{bar()}
```

#### Details
i get babili from npm

```bash
npm i -g babili

babili src -d lib
```

**Comment by j-f1** [comment]
This is shorter:
```js
if(condition)foo();else bar()
```

**Comment by boopathi** [comment]
Doesn't it transform to `condition ? foo() : bar()` ?

**Comment by Wang-NQXB** [comment]
it is just a example， code is more complex in practice.  the problem i wanna say is  babili removed the bracket of the if statement and shorter the statement to one line and no semicolon added before else statement

**Comment by Wang-NQXB** [comment]
sorry it's my own problem,  i figured it out, you can close this.  thx
