### ISSUE TITLE
Transform iife into iiafe

### ISSUE THREAD

**Issue by frzi** [babel/babili#642]
What are the thoughts of transforming iife to iiafe? (immediately invoked **arrow** function expressions)?

#### Input Code
```js
(function () {
   /* ... */
})();

// or

(function () {
   /* ... */
}());
```

#### Transformed Code
```js
(_=>{/*...*/})()
```

**Comment by j-f1** [comment]
What about just a block?

```js
{/*...*/}
```

**Comment by frzi** [comment]
Transforming iifes into a simple block would work for iife at top level, without any arguments.

But a little trickier otherwise, I think(?).
```js
let dynamicClass = (function ($) {
    function MyClass() {}
    MyClass.$ = $
    return MyClass
})(jQuery)
```
which now transform to:
```js
let dynamicClass=function(a){function b(){}return b.$=a,b}(jQuery);
```
With an iiafe:
```js
let dynamicClass=(a=>{function b(){}return b.$=a,b})(jQuery);
```

**Comment by boopathi** [comment]
This has already been brought up. There is an issue for that already - #428 . Closing this and tracking it there.
