### ISSUE TITLE
Does not remove comments.

### ISSUE THREAD

**Issue by trusktr** [babel/babili#644]
Babili is a minifier. Removing comments is part of minification.

https://github.com/babel/babili/issues/217

**Comment by trusktr** [comment]
For example, Rollup users using Babili (but not Babel) can either

- Add babel just to delete comments
- Add the unofficial rollup-plugin-cleanup just to make Rollup first remove comments.

**Comment by boopathi** [comment]
Babili doesn't remove comments. Comments are removed by babel the tool which babili depends on as a part of the generation phase (babel-generator). Babili is just a babel-preset with a set of transformations. So, if you want to control the comments output, you can configure it with the tool which uses babel+babili.

For rollup, rollup-plugin-babili takes a comments option - https://github.com/Comandeer/rollup-plugin-babili/blob/002ec6366ab9a44296a15d3318c644d0ef2d6ad9/src/index.js#L26 

For webpack, there is a comments option too - https://github.com/webpack-contrib/babili-webpack-plugin#overrides

For gulp-babili, https://github.com/babel/babili/tree/master/packages/gulp-babili#overrides, there is a `comments` option, but not documented yet - but the same as babili-webpack-plugin. Would appreciate a PR.

**Comment by trusktr** [comment]
@boopathi Oops, sorry, I missed that option. Thanks!

**Comment by depoulo** [comment]
@boopathi but doesn't that also remove license comments?

**Comment by depoulo** [comment]
@boopathi can you please make it default behaviour that all non-license comments are stripped in gulp-babel-minify? It feels extremely odd having to write `.pipe(minify({}, {comments: /@preserve|@licen(s|c)e/}))` for achieving this, especially since that option is, as you say, undocumented.

**Comment by depoulo** [comment]
Sorry I was just confused. The default does **not** include the `@` signs, contrary to what is stated in the babili-webpack-plugin README #overrides.

This in turn causes comments like this one from lodash to be preserved (pun intended, since that comment includes the string `preserve`:

```/*
     * Creates an array of elements, sorted in ascending order by the results of
     * running each element in a collection thru each iteratee. This method
     * performs a stable sort, that is, it preserves the original sort order of
     * equal elements. The iteratees are invoked with one argument: (value).
     *
     * @static
     * @memberOf _
     * @since 0.1.0
     * @category Collection
     * @param {Array|Object} collection The collection to iterate over.
     * @param {...(Function|Function[])} [iteratees=[_.identity]]
     *  The iteratees to sort by.
     * @returns {Array} Returns the new sorted array.
     * @example
     *
     * var users = [
     *   { 'user': 'fred',   'age': 48 },
     *   { 'user': 'barney', 'age': 36 },
     *   { 'user': 'fred',   'age': 40 },
     *   { 'user': 'barney', 'age': 34 }
     * ];
     *
     * _.sortBy(users, [function(o) { return o.user; }]);
     * // => objects for [['barney', 36], ['barney', 34], ['fred', 48], ['fred', 40]]
     *
     * _.sortBy(users, ['user', 'age']);
     * // => objects for [['barney', 34], ['barney', 36], ['fred', 40], ['fred', 48]]
     */
```
