### ISSUE TITLE
Remove unused calls to pure functions

### ISSUE THREAD

**Issue by j-f1** [babel/babili#647]
Babili could use an `@pure` JSDoc tag to determine which functions are pure, then remove unused calls to them.

AST Explorer with code + example: https://astexplorer.net/#/gist/bdcbc34df3916d324454a332988503c7/7c39cede7af9cc9244f89876bb8339a5a4fb3d37

In:
```js
/** @pure */
const myPureFunc = () => {}
myPureFunc()
```

Out:
```js
/** @pure */
const myPureFunc = () => {}
```

**Comment by nicolo-ribaudo** [comment]
Instead of `@pure` Babili could use `#__PURE__`, like Uglify: mishoo/UglifyJS2#1448, babel/babel#5632

**Comment by hzoo** [comment]
This is a similar request to https://github.com/babel/babel/issues/5632? Referencing the same issue too. I'm already in favor of doing it

**Comment by j-f1** [comment]
Sort of — this one will strip out calls to pure functions, while that one wants to add an annotation to functions wrapping transpiled classes.

**Comment by boopathi** [comment]
Duplicate #520
