### ISSUE TITLE
The cli doesn't pass in comments: false

### ISSUE THREAD

**Issue by amasad** [babel/babili#67]
It seems like `comments: false` cannot passed from the preset nor the cli 😕

**Comment by blacksonic** [comment]
Any update on this? It would cleanup bundles when using it instead of UglifyJS.
[Example repository](https://github.com/blacksonic/babel-webpack-tree-shaking) for it.

**Comment by Kovensky** [comment]
`--no-comments` works in the cli, but it strips even "strong" comments like those used for licenses (i.e. there's no equivalent to uglify's "some" option).

**Comment by blacksonic** [comment]
Thanks, it solved the issue. Finally tree-shaking really works with Webpack + Babel + Babili :+1:

**Comment by swernerx** [comment]
Just curious as I am bound to Webpack where CLI options do not work: Where is the "no-comments" flag implemented? Because Babel actually seems to only know "--comments false" ... at least this is what I see in `babel-core/lib/transformation/file/options/config.js`

**Comment by hzoo** [comment]
should be able to do

```js
{ "comments": false }
```

in your .babelrc/query

**Comment by blacksonic** [comment]
What would be the resulting ```.babelrc``` file? This setup doesn't seem to work.

```
{
  "presets": ["latest"],
  "comments": false
}
```

**Comment by hzoo** [comment]
Wow I don't understand.. it seems that it doesn't allow false given https://github.com/babel/babel/blob/b871a49e3a681980945370a8b468117ccf759cef/packages/babel-generator/src/index.js#L56

`comments: opts.comments == null || opts.comments,` since false == null -> true

**Comment by brianblakely** [comment]
For me, the latest babili as of writing properly removes non-Webpack comments, using this loader config:

```
{
  test: /\.js$/,
  loader: `babel`,
  query: {
    presets: [`babili`],
    plugins: [`transform-es2015-modules-commonjs`],
    comments: false
  }
}
```

Not sure if there is a way for Babili to minify the Webpack bundle itself?  Perhaps that's why Uglify is a Webpack plugin, and the same might need to be done for Babili.

**Comment by blacksonic** [comment]
@brianblakely your wish came true https://github.com/boopathi/babili-webpack-plugin

**Comment by brianblakely** [comment]
😮

Thanks @boopathi

**Comment by knpwrs** [comment]
I believe this is related? https://phabricator.babeljs.io/T6858

**Comment by hzoo** [comment]
a PR with https://github.com/babel/babel/pull/4507

Going to close as dup of https://github.com/babel/babel/issues/3899 since it's Babel issue. Will be out in the next release
