### ISSUE TITLE
Pronunciation

### ISSUE THREAD

**Issue by klimashkin** [babel/babili#94]
Would be great to fix right pronunciation of 'babili' at the beginning.

So, seems like it's esperanto word (chat), in this case stress on the second syllable. Like in Spanish: https://translate.google.ru/?source=osdd#es/en/babili

If the babili's Makers have their own version, talk now please! :)

**Comment by kangax** [comment]
"Bābili" is "Babylon" in Akkadian — https://en.wikipedia.org/wiki/Babylon

That's what we were going for, unrelated to Esperanto :)

**Comment by klimashkin** [comment]
Do we need to dig up couple Akkadians to ask them how they pronounce it? :)
